// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conversionFunnel = `-- name: ConversionFunnel :many
SELECT stage, COUNT(*)::int as count
FROM leads
WHERE workspace_id = $1
GROUP BY stage
`

type ConversionFunnelRow struct {
	Stage LeadStage `json:"stage"`
	Count int32     `json:"count"`
}

func (q *Queries) ConversionFunnel(ctx context.Context, workspaceID string) ([]ConversionFunnelRow, error) {
	rows, err := q.db.Query(ctx, conversionFunnel, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionFunnelRow{}
	for rows.Next() {
		var i ConversionFunnelRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveKeywords = `-- name: CountActiveKeywords :one
SELECT COUNT(*)::int as count FROM keywords
WHERE workspace_id = $1 AND is_active = true
`

func (q *Queries) CountActiveKeywords(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveKeywords, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countConvertedLeads = `-- name: CountConvertedLeads :one
SELECT COUNT(*)::int as count FROM leads
WHERE workspace_id = $1 AND stage = 'converted'
`

func (q *Queries) CountConvertedLeads(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countConvertedLeads, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countMentions30d = `-- name: CountMentions30d :one
SELECT COUNT(*)::int as count FROM mentions
WHERE workspace_id = $1 AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) CountMentions30d(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMentions30d, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countNewMentions = `-- name: CountNewMentions :one
SELECT COUNT(*)::int as count FROM mentions
WHERE workspace_id = $1 AND status = 'new'
`

func (q *Queries) CountNewMentions(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNewMentions, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countRepliesPosted30d = `-- name: CountRepliesPosted30d :one
SELECT COUNT(*)::int as count FROM replies
WHERE workspace_id = $1 AND status = 'posted'
AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) CountRepliesPosted30d(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countRepliesPosted30d, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTotalLeads = `-- name: CountTotalLeads :one
SELECT COUNT(*)::int as count FROM leads
WHERE workspace_id = $1
`

func (q *Queries) CountTotalLeads(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countTotalLeads, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const mentionsPerDay = `-- name: MentionsPerDay :many
SELECT DATE(created_at) as day, COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY day
`

type MentionsPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int32       `json:"count"`
}

func (q *Queries) MentionsPerDay(ctx context.Context, workspaceID string) ([]MentionsPerDayRow, error) {
	rows, err := q.db.Query(ctx, mentionsPerDay, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionsPerDayRow{}
	for rows.Next() {
		var i MentionsPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionsPerIntent = `-- name: MentionsPerIntent :many
SELECT intent, COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
AND intent IS NOT NULL
AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY intent
`

type MentionsPerIntentRow struct {
	Intent NullIntentType `json:"intent"`
	Count  int32          `json:"count"`
}

func (q *Queries) MentionsPerIntent(ctx context.Context, workspaceID string) ([]MentionsPerIntentRow, error) {
	rows, err := q.db.Query(ctx, mentionsPerIntent, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionsPerIntentRow{}
	for rows.Next() {
		var i MentionsPerIntentRow
		if err := rows.Scan(&i.Intent, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionsPerPlatform = `-- name: MentionsPerPlatform :many
SELECT platform, COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY platform
`

type MentionsPerPlatformRow struct {
	Platform string `json:"platform"`
	Count    int32  `json:"count"`
}

func (q *Queries) MentionsPerPlatform(ctx context.Context, workspaceID string) ([]MentionsPerPlatformRow, error) {
	rows, err := q.db.Query(ctx, mentionsPerPlatform, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionsPerPlatformRow{}
	for rows.Next() {
		var i MentionsPerPlatformRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyStats = `-- name: ReplyStats :many
SELECT status, COUNT(*)::int as count
FROM replies
WHERE workspace_id = $1
AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY status
`

type ReplyStatsRow struct {
	Status ReplyStatus `json:"status"`
	Count  int32       `json:"count"`
}

func (q *Queries) ReplyStats(ctx context.Context, workspaceID string) ([]ReplyStatsRow, error) {
	rows, err := q.db.Query(ctx, replyStats, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplyStatsRow{}
	for rows.Next() {
		var i ReplyStatsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topKeywords = `-- name: TopKeywords :many
SELECT k.term, COUNT(m.id)::int as mention_count
FROM keywords k
LEFT JOIN mentions m ON (m.keyword_id = k.id OR k.term = ANY(m.keyword_matches))
AND m.workspace_id = k.workspace_id
AND m.created_at >= NOW() - INTERVAL '30 days'
WHERE k.workspace_id = $1
GROUP BY k.id, k.term
ORDER BY mention_count DESC
LIMIT 10
`

type TopKeywordsRow struct {
	Term         string `json:"term"`
	MentionCount int32  `json:"mention_count"`
}

func (q *Queries) TopKeywords(ctx context.Context, workspaceID string) ([]TopKeywordsRow, error) {
	rows, err := q.db.Query(ctx, topKeywords, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopKeywordsRow{}
	for rows.Next() {
		var i TopKeywordsRow
		if err := rows.Scan(&i.Term, &i.MentionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
