// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution.sql

package database

import (
	"context"
)

const replyStyleAttribution = `-- name: ReplyStyleAttribution :many
SELECT
    COALESCE(r.template_style, 'unknown') AS template_style,
    COUNT(*)::int AS reply_count,
    COUNT(*) FILTER (WHERE r.status = 'posted')::int AS posted_count,
    COALESCE(SUM(u.click_count), 0)::int AS click_count,
    COALESCE(SUM(u.signup_count), 0)::int AS signup_count
FROM replies r
LEFT JOIN utm_links u ON r.utm_link_id = u.id
WHERE r.workspace_id = $1
  AND r.created_at >= NOW() - INTERVAL '30 days'
GROUP BY 1
ORDER BY signup_count DESC, click_count DESC
`

type ReplyStyleAttributionRow struct {
	TemplateStyle string `json:"template_style"`
	ReplyCount    int32  `json:"reply_count"`
	PostedCount   int32  `json:"posted_count"`
	ClickCount    int32  `json:"click_count"`
	SignupCount   int32  `json:"signup_count"`
}

func (q *Queries) ReplyStyleAttribution(ctx context.Context, workspaceID string) ([]ReplyStyleAttributionRow, error) {
	rows, err := q.db.Query(ctx, replyStyleAttribution, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplyStyleAttributionRow{}
	for rows.Next() {
		var i ReplyStyleAttributionRow
		if err := rows.Scan(
			&i.TemplateStyle,
			&i.ReplyCount,
			&i.PostedCount,
			&i.ClickCount,
			&i.SignupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReplyMetadata = `-- name: UpdateReplyMetadata :one
UPDATE replies
SET metadata = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used, metadata
`

type UpdateReplyMetadataParams struct {
	Metadata    []byte `json:"metadata"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateReplyMetadata(ctx context.Context, arg UpdateReplyMetadataParams) (Reply, error) {
	row := q.db.QueryRow(ctx, updateReplyMetadata, arg.Metadata, arg.ID, arg.WorkspaceID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
		&i.Metadata,
	)
	return i, err
}
