// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*)::int as count FROM documents
WHERE workspace_id = $1 AND is_active = true
`

func (q *Queries) CountDocuments(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countDocuments, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    workspace_id, title, content, content_type, source_url, file_size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at
`

type CreateDocumentParams struct {
	WorkspaceID   string      `json:"workspace_id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	ContentType   string      `json:"content_type"`
	SourceUrl     pgtype.Text `json:"source_url"`
	FileSizeBytes pgtype.Int4 `json:"file_size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.ContentType,
		arg.SourceUrl,
		arg.FileSizeBytes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
UPDATE documents
SET is_active = false
WHERE id = $1 AND workspace_id = $2
`

type DeleteDocumentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.WorkspaceID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at FROM documents
WHERE id = $1 AND workspace_id = $2
`

type GetDocumentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at FROM documents
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Content,
			&i.ContentType,
			&i.SourceUrl,
			&i.FileSizeBytes,
			&i.ChunkCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $1,
    content = $2,
    is_active = $3
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at
`

type UpdateDocumentParams struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsActive    bool   `json:"is_active"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Title,
		arg.Content,
		arg.IsActive,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentChunkCount = `-- name: UpdateDocumentChunkCount :exec
UPDATE documents
SET chunk_count = $1
WHERE id = $2
`

type UpdateDocumentChunkCountParams struct {
	ChunkCount int32  `json:"chunk_count"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDocumentChunkCount(ctx context.Context, arg UpdateDocumentChunkCountParams) error {
	_, err := q.db.Exec(ctx, updateDocumentChunkCount, arg.ChunkCount, arg.ID)
	return err
}
