// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*)::int as count FROM documents
WHERE workspace_id = $1 AND is_active = true
`

func (q *Queries) CountDocuments(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countDocuments, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    workspace_id, title, content, content_type, source_url, file_size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at
`

type CreateDocumentParams struct {
	WorkspaceID   string      `json:"workspace_id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	ContentType   string      `json:"content_type"`
	SourceUrl     pgtype.Text `json:"source_url"`
	FileSizeBytes pgtype.Int4 `json:"file_size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.ContentType,
		arg.SourceUrl,
		arg.FileSizeBytes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
UPDATE documents
SET is_active = false
WHERE id = $1 AND workspace_id = $2
`

type DeleteDocumentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.WorkspaceID)
	return err
}

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
DELETE FROM document_chunks
WHERE document_id = $1 AND workspace_id = $2
`

type DeleteDocumentChunksParams struct {
	DocumentID  string `json:"document_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteDocumentChunks(ctx context.Context, arg DeleteDocumentChunksParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentChunks, arg.DocumentID, arg.WorkspaceID)
	return err
}

const findSimilarDocumentChunks = `-- name: FindSimilarDocumentChunks :many
SELECT
    dc.id,
    dc.document_id,
    dc.content,
    dc.section_title,
    (1 - (dc.embedding <=> $1::vector))::float8 AS similarity
FROM document_chunks dc
WHERE dc.workspace_id = $2
ORDER BY dc.embedding <=> $1::vector
LIMIT $3
`

type FindSimilarDocumentChunksParams struct {
	QueryEmbedding *pgvector_go.Vector `json:"query_embedding"`
	WorkspaceID    string              `json:"workspace_id"`
	Lim            int32               `json:"lim"`
}

type FindSimilarDocumentChunksRow struct {
	ID           string      `json:"id"`
	DocumentID   string      `json:"document_id"`
	Content      string      `json:"content"`
	SectionTitle pgtype.Text `json:"section_title"`
	Similarity   float64     `json:"similarity"`
}

func (q *Queries) FindSimilarDocumentChunks(ctx context.Context, arg FindSimilarDocumentChunksParams) ([]FindSimilarDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, findSimilarDocumentChunks, arg.QueryEmbedding, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarDocumentChunksRow{}
	for rows.Next() {
		var i FindSimilarDocumentChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.SectionTitle,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at FROM documents
WHERE id = $1 AND workspace_id = $2 AND is_active = true
`

type GetDocumentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentChunk = `-- name: InsertDocumentChunk :one
INSERT INTO document_chunks (
    document_id, workspace_id, content, embedding, chunk_index, section_title
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, document_id, workspace_id, content, content_tsv, embedding, chunk_index, section_title, metadata, token_count, created_at
`

type InsertDocumentChunkParams struct {
	DocumentID   string              `json:"document_id"`
	WorkspaceID  string              `json:"workspace_id"`
	Content      string              `json:"content"`
	Embedding    *pgvector_go.Vector `json:"embedding"`
	ChunkIndex   int32               `json:"chunk_index"`
	SectionTitle pgtype.Text         `json:"section_title"`
}

func (q *Queries) InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, insertDocumentChunk,
		arg.DocumentID,
		arg.WorkspaceID,
		arg.Content,
		arg.Embedding,
		arg.ChunkIndex,
		arg.SectionTitle,
	)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.WorkspaceID,
		&i.Content,
		&i.ContentTsv,
		&i.Embedding,
		&i.ChunkIndex,
		&i.SectionTitle,
		&i.Metadata,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at FROM documents
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Content,
			&i.ContentType,
			&i.SourceUrl,
			&i.FileSizeBytes,
			&i.ChunkCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $1,
    content = $2,
    is_active = $3
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, title, content, content_type, source_url, file_size_bytes, chunk_count, is_active, created_at, updated_at
`

type UpdateDocumentParams struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsActive    bool   `json:"is_active"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Title,
		arg.Content,
		arg.IsActive,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.ContentType,
		&i.SourceUrl,
		&i.FileSizeBytes,
		&i.ChunkCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentChunkCount = `-- name: UpdateDocumentChunkCount :exec
UPDATE documents
SET chunk_count = $1
WHERE id = $2
`

type UpdateDocumentChunkCountParams struct {
	ChunkCount int32  `json:"chunk_count"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDocumentChunkCount(ctx context.Context, arg UpdateDocumentChunkCountParams) error {
	_, err := q.db.Exec(ctx, updateDocumentChunkCount, arg.ChunkCount, arg.ID)
	return err
}
