// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenDeadLetterEvents = `-- name: CountOpenDeadLetterEvents :one
SELECT COUNT(*)::bigint AS count
FROM dead_letter_events
WHERE resolution_status = 'open'
`

func (q *Queries) CountOpenDeadLetterEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDeadLetterEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConsumerProcessedEvent = `-- name: CreateConsumerProcessedEvent :one
INSERT INTO consumer_processed_events (
    consumer_group, consumer_name, event_id, stream_name, redis_message_id,
    workspace_id, result_status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
) RETURNING id, consumer_group, consumer_name, event_id, stream_name, redis_message_id, workspace_id, processed_at, result_status
`

type CreateConsumerProcessedEventParams struct {
	ConsumerGroup  string      `json:"consumer_group"`
	ConsumerName   string      `json:"consumer_name"`
	EventID        string      `json:"event_id"`
	StreamName     string      `json:"stream_name"`
	RedisMessageID string      `json:"redis_message_id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ResultStatus   string      `json:"result_status"`
}

func (q *Queries) CreateConsumerProcessedEvent(ctx context.Context, arg CreateConsumerProcessedEventParams) (ConsumerProcessedEvent, error) {
	row := q.db.QueryRow(ctx, createConsumerProcessedEvent,
		arg.ConsumerGroup,
		arg.ConsumerName,
		arg.EventID,
		arg.StreamName,
		arg.RedisMessageID,
		arg.WorkspaceID,
		arg.ResultStatus,
	)
	var i ConsumerProcessedEvent
	err := row.Scan(
		&i.ID,
		&i.ConsumerGroup,
		&i.ConsumerName,
		&i.EventID,
		&i.StreamName,
		&i.RedisMessageID,
		&i.WorkspaceID,
		&i.ProcessedAt,
		&i.ResultStatus,
	)
	return i, err
}

const createDeadLetterEvent = `-- name: CreateDeadLetterEvent :one
INSERT INTO dead_letter_events (
    event_id, stream_name, consumer_group, consumer_name, workspace_id,
    redis_message_id, payload, error_code, error_class, error_message,
    stack_excerpt, retry_count, first_seen_at, last_seen_at, resolution_status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
) RETURNING id, event_id, stream_name, consumer_group, consumer_name, workspace_id, redis_message_id, payload, error_code, error_class, error_message, stack_excerpt, retry_count, first_seen_at, last_seen_at, resolved_at, resolution_status, created_at
`

type CreateDeadLetterEventParams struct {
	EventID          string      `json:"event_id"`
	StreamName       string      `json:"stream_name"`
	ConsumerGroup    string      `json:"consumer_group"`
	ConsumerName     string      `json:"consumer_name"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	RedisMessageID   pgtype.Text `json:"redis_message_id"`
	Payload          []byte      `json:"payload"`
	ErrorCode        pgtype.Text `json:"error_code"`
	ErrorClass       string      `json:"error_class"`
	ErrorMessage     string      `json:"error_message"`
	StackExcerpt     pgtype.Text `json:"stack_excerpt"`
	RetryCount       int32       `json:"retry_count"`
	FirstSeenAt      time.Time   `json:"first_seen_at"`
	LastSeenAt       time.Time   `json:"last_seen_at"`
	ResolutionStatus string      `json:"resolution_status"`
}

func (q *Queries) CreateDeadLetterEvent(ctx context.Context, arg CreateDeadLetterEventParams) (DeadLetterEvent, error) {
	row := q.db.QueryRow(ctx, createDeadLetterEvent,
		arg.EventID,
		arg.StreamName,
		arg.ConsumerGroup,
		arg.ConsumerName,
		arg.WorkspaceID,
		arg.RedisMessageID,
		arg.Payload,
		arg.ErrorCode,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.StackExcerpt,
		arg.RetryCount,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.ResolutionStatus,
	)
	var i DeadLetterEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.ConsumerGroup,
		&i.ConsumerName,
		&i.WorkspaceID,
		&i.RedisMessageID,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.StackExcerpt,
		&i.RetryCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.ResolutionStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_log (
    event_id, stream_name, event_type, schema_version, workspace_id,
    aggregate_type, aggregate_id, producer, payload, idempotency_key,
    correlation_id, causation_id, trace_id, occurred_at, replay_of_event_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
) RETURNING id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at
`

type CreateEventLogParams struct {
	EventID         string      `json:"event_id"`
	StreamName      string      `json:"stream_name"`
	EventType       string      `json:"event_type"`
	SchemaVersion   int32       `json:"schema_version"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	AggregateType   string      `json:"aggregate_type"`
	AggregateID     string      `json:"aggregate_id"`
	Producer        string      `json:"producer"`
	Payload         []byte      `json:"payload"`
	IdempotencyKey  string      `json:"idempotency_key"`
	CorrelationID   pgtype.Text `json:"correlation_id"`
	CausationID     pgtype.Text `json:"causation_id"`
	TraceID         pgtype.Text `json:"trace_id"`
	OccurredAt      time.Time   `json:"occurred_at"`
	ReplayOfEventID pgtype.UUID `json:"replay_of_event_id"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, createEventLog,
		arg.EventID,
		arg.StreamName,
		arg.EventType,
		arg.SchemaVersion,
		arg.WorkspaceID,
		arg.AggregateType,
		arg.AggregateID,
		arg.Producer,
		arg.Payload,
		arg.IdempotencyKey,
		arg.CorrelationID,
		arg.CausationID,
		arg.TraceID,
		arg.OccurredAt,
		arg.ReplayOfEventID,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.EventType,
		&i.SchemaVersion,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Producer,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.CausationID,
		&i.TraceID,
		&i.OccurredAt,
		&i.RedisMessageID,
		&i.PublishStatus,
		&i.PublishAttempts,
		&i.LastError,
		&i.ReplayOfEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventReplay = `-- name: CreateEventReplay :one
INSERT INTO event_replays (
    requested_by, stream_name, consumer_group, event_type, workspace_id,
    aggregate_type, aggregate_id, from_occurred_at, to_occurred_at,
    replay_mode, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
) RETURNING id, requested_by, stream_name, consumer_group, event_type, workspace_id, aggregate_type, aggregate_id, from_occurred_at, to_occurred_at, replay_mode, status, replayed_count, last_error, created_at, updated_at
`

type CreateEventReplayParams struct {
	RequestedBy    pgtype.UUID        `json:"requested_by"`
	StreamName     string             `json:"stream_name"`
	ConsumerGroup  pgtype.Text        `json:"consumer_group"`
	EventType      pgtype.Text        `json:"event_type"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	AggregateID    pgtype.Text        `json:"aggregate_id"`
	FromOccurredAt pgtype.Timestamptz `json:"from_occurred_at"`
	ToOccurredAt   pgtype.Timestamptz `json:"to_occurred_at"`
	ReplayMode     string             `json:"replay_mode"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateEventReplay(ctx context.Context, arg CreateEventReplayParams) (EventReplay, error) {
	row := q.db.QueryRow(ctx, createEventReplay,
		arg.RequestedBy,
		arg.StreamName,
		arg.ConsumerGroup,
		arg.EventType,
		arg.WorkspaceID,
		arg.AggregateType,
		arg.AggregateID,
		arg.FromOccurredAt,
		arg.ToOccurredAt,
		arg.ReplayMode,
		arg.Status,
	)
	var i EventReplay
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.StreamName,
		&i.ConsumerGroup,
		&i.EventType,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.FromOccurredAt,
		&i.ToOccurredAt,
		&i.ReplayMode,
		&i.Status,
		&i.ReplayedCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventLogByEventID = `-- name: GetEventLogByEventID :one
SELECT id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at FROM event_log
WHERE event_id = $1
`

func (q *Queries) GetEventLogByEventID(ctx context.Context, eventID string) (EventLog, error) {
	row := q.db.QueryRow(ctx, getEventLogByEventID, eventID)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.EventType,
		&i.SchemaVersion,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Producer,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.CausationID,
		&i.TraceID,
		&i.OccurredAt,
		&i.RedisMessageID,
		&i.PublishStatus,
		&i.PublishAttempts,
		&i.LastError,
		&i.ReplayOfEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasConsumerProcessedEvent = `-- name: HasConsumerProcessedEvent :one
SELECT EXISTS (
    SELECT 1
    FROM consumer_processed_events
    WHERE consumer_group = $1
      AND event_id = $2
) AS processed
`

type HasConsumerProcessedEventParams struct {
	ConsumerGroup string `json:"consumer_group"`
	EventID       string `json:"event_id"`
}

func (q *Queries) HasConsumerProcessedEvent(ctx context.Context, arg HasConsumerProcessedEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasConsumerProcessedEvent, arg.ConsumerGroup, arg.EventID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const listConsumerCheckpoints = `-- name: ListConsumerCheckpoints :many
SELECT id, stream_name, consumer_group, consumer_name, last_redis_message_id, pending_count, last_error, heartbeat_at, updated_at FROM consumer_checkpoints
ORDER BY heartbeat_at DESC
`

func (q *Queries) ListConsumerCheckpoints(ctx context.Context) ([]ConsumerCheckpoint, error) {
	rows, err := q.db.Query(ctx, listConsumerCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsumerCheckpoint{}
	for rows.Next() {
		var i ConsumerCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.StreamName,
			&i.ConsumerGroup,
			&i.ConsumerName,
			&i.LastRedisMessageID,
			&i.PendingCount,
			&i.LastError,
			&i.HeartbeatAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLogByWorkspace = `-- name: ListEventLogByWorkspace :many
SELECT id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at FROM event_log
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListEventLogByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Off         int32       `json:"off"`
	Lim         int32       `json:"lim"`
}

func (q *Queries) ListEventLogByWorkspace(ctx context.Context, arg ListEventLogByWorkspaceParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, listEventLogByWorkspace, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StreamName,
			&i.EventType,
			&i.SchemaVersion,
			&i.WorkspaceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Producer,
			&i.Payload,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.CausationID,
			&i.TraceID,
			&i.OccurredAt,
			&i.RedisMessageID,
			&i.PublishStatus,
			&i.PublishAttempts,
			&i.LastError,
			&i.ReplayOfEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventReplays = `-- name: ListEventReplays :many
SELECT id, requested_by, stream_name, consumer_group, event_type, workspace_id, aggregate_type, aggregate_id, from_occurred_at, to_occurred_at, replay_mode, status, replayed_count, last_error, created_at, updated_at FROM event_replays
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListEventReplaysParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListEventReplays(ctx context.Context, arg ListEventReplaysParams) ([]EventReplay, error) {
	rows, err := q.db.Query(ctx, listEventReplays, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventReplay{}
	for rows.Next() {
		var i EventReplay
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.StreamName,
			&i.ConsumerGroup,
			&i.EventType,
			&i.WorkspaceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.FromOccurredAt,
			&i.ToOccurredAt,
			&i.ReplayMode,
			&i.Status,
			&i.ReplayedCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDeadLetterEvents = `-- name: ListOpenDeadLetterEvents :many
SELECT id, event_id, stream_name, consumer_group, consumer_name, workspace_id, redis_message_id, payload, error_code, error_class, error_message, stack_excerpt, retry_count, first_seen_at, last_seen_at, resolved_at, resolution_status, created_at FROM dead_letter_events
WHERE resolution_status = 'open'
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListOpenDeadLetterEventsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListOpenDeadLetterEvents(ctx context.Context, arg ListOpenDeadLetterEventsParams) ([]DeadLetterEvent, error) {
	rows, err := q.db.Query(ctx, listOpenDeadLetterEvents, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterEvent{}
	for rows.Next() {
		var i DeadLetterEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StreamName,
			&i.ConsumerGroup,
			&i.ConsumerName,
			&i.WorkspaceID,
			&i.RedisMessageID,
			&i.Payload,
			&i.ErrorCode,
			&i.ErrorClass,
			&i.ErrorMessage,
			&i.StackExcerpt,
			&i.RetryCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.ResolutionStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayableEvents = `-- name: ListReplayableEvents :many
SELECT id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at FROM event_log
WHERE stream_name = $1
  AND ($2 = '' OR event_type = $2)
  AND ($3::uuid IS NULL OR workspace_id = $3)
  AND ($4 = '' OR aggregate_type = $4)
  AND ($5 = '' OR aggregate_id = $5)
  AND ($6::timestamptz IS NULL OR occurred_at >= $6)
  AND ($7::timestamptz IS NULL OR occurred_at <= $7)
ORDER BY occurred_at ASC
LIMIT $8
`

type ListReplayableEventsParams struct {
	StreamName     string      `json:"stream_name"`
	EventType      interface{} `json:"event_type"`
	WorkspaceID    string      `json:"workspace_id"`
	AggregateType  interface{} `json:"aggregate_type"`
	AggregateID    interface{} `json:"aggregate_id"`
	FromOccurredAt time.Time   `json:"from_occurred_at"`
	ToOccurredAt   time.Time   `json:"to_occurred_at"`
	Lim            int32       `json:"lim"`
}

func (q *Queries) ListReplayableEvents(ctx context.Context, arg ListReplayableEventsParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, listReplayableEvents,
		arg.StreamName,
		arg.EventType,
		arg.WorkspaceID,
		arg.AggregateType,
		arg.AggregateID,
		arg.FromOccurredAt,
		arg.ToOccurredAt,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StreamName,
			&i.EventType,
			&i.SchemaVersion,
			&i.WorkspaceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.Producer,
			&i.Payload,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.CausationID,
			&i.TraceID,
			&i.OccurredAt,
			&i.RedisMessageID,
			&i.PublishStatus,
			&i.PublishAttempts,
			&i.LastError,
			&i.ReplayOfEventID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventLogPublishFailed = `-- name: MarkEventLogPublishFailed :one
UPDATE event_log
SET publish_status = $1,
    publish_attempts = publish_attempts + 1,
    last_error = $2,
    updated_at = NOW()
WHERE event_id = $3
RETURNING id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at
`

type MarkEventLogPublishFailedParams struct {
	PublishStatus string      `json:"publish_status"`
	LastError     pgtype.Text `json:"last_error"`
	EventID       string      `json:"event_id"`
}

func (q *Queries) MarkEventLogPublishFailed(ctx context.Context, arg MarkEventLogPublishFailedParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, markEventLogPublishFailed, arg.PublishStatus, arg.LastError, arg.EventID)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.EventType,
		&i.SchemaVersion,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Producer,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.CausationID,
		&i.TraceID,
		&i.OccurredAt,
		&i.RedisMessageID,
		&i.PublishStatus,
		&i.PublishAttempts,
		&i.LastError,
		&i.ReplayOfEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEventLogPublished = `-- name: MarkEventLogPublished :one
UPDATE event_log
SET redis_message_id = $1,
    publish_status = $2,
    publish_attempts = publish_attempts + 1,
    last_error = $3,
    updated_at = NOW()
WHERE event_id = $4
RETURNING id, event_id, stream_name, event_type, schema_version, workspace_id, aggregate_type, aggregate_id, producer, payload, idempotency_key, correlation_id, causation_id, trace_id, occurred_at, redis_message_id, publish_status, publish_attempts, last_error, replay_of_event_id, created_at, updated_at
`

type MarkEventLogPublishedParams struct {
	RedisMessageID pgtype.Text `json:"redis_message_id"`
	PublishStatus  string      `json:"publish_status"`
	LastError      pgtype.Text `json:"last_error"`
	EventID        string      `json:"event_id"`
}

func (q *Queries) MarkEventLogPublished(ctx context.Context, arg MarkEventLogPublishedParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, markEventLogPublished,
		arg.RedisMessageID,
		arg.PublishStatus,
		arg.LastError,
		arg.EventID,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.EventType,
		&i.SchemaVersion,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.Producer,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.CausationID,
		&i.TraceID,
		&i.OccurredAt,
		&i.RedisMessageID,
		&i.PublishStatus,
		&i.PublishAttempts,
		&i.LastError,
		&i.ReplayOfEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDeadLetterEvent = `-- name: ResolveDeadLetterEvent :one
UPDATE dead_letter_events
SET resolution_status = $1,
    resolved_at = $2,
    last_seen_at = NOW()
WHERE id = $3
RETURNING id, event_id, stream_name, consumer_group, consumer_name, workspace_id, redis_message_id, payload, error_code, error_class, error_message, stack_excerpt, retry_count, first_seen_at, last_seen_at, resolved_at, resolution_status, created_at
`

type ResolveDeadLetterEventParams struct {
	ResolutionStatus string             `json:"resolution_status"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ID               string             `json:"id"`
}

func (q *Queries) ResolveDeadLetterEvent(ctx context.Context, arg ResolveDeadLetterEventParams) (DeadLetterEvent, error) {
	row := q.db.QueryRow(ctx, resolveDeadLetterEvent, arg.ResolutionStatus, arg.ResolvedAt, arg.ID)
	var i DeadLetterEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StreamName,
		&i.ConsumerGroup,
		&i.ConsumerName,
		&i.WorkspaceID,
		&i.RedisMessageID,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.StackExcerpt,
		&i.RetryCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.ResolutionStatus,
		&i.CreatedAt,
	)
	return i, err
}

const updateEventReplayStatus = `-- name: UpdateEventReplayStatus :one
UPDATE event_replays
SET status = $1,
    replayed_count = $2,
    last_error = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, requested_by, stream_name, consumer_group, event_type, workspace_id, aggregate_type, aggregate_id, from_occurred_at, to_occurred_at, replay_mode, status, replayed_count, last_error, created_at, updated_at
`

type UpdateEventReplayStatusParams struct {
	Status        string      `json:"status"`
	ReplayedCount int32       `json:"replayed_count"`
	LastError     pgtype.Text `json:"last_error"`
	ID            string      `json:"id"`
}

func (q *Queries) UpdateEventReplayStatus(ctx context.Context, arg UpdateEventReplayStatusParams) (EventReplay, error) {
	row := q.db.QueryRow(ctx, updateEventReplayStatus,
		arg.Status,
		arg.ReplayedCount,
		arg.LastError,
		arg.ID,
	)
	var i EventReplay
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.StreamName,
		&i.ConsumerGroup,
		&i.EventType,
		&i.WorkspaceID,
		&i.AggregateType,
		&i.AggregateID,
		&i.FromOccurredAt,
		&i.ToOccurredAt,
		&i.ReplayMode,
		&i.Status,
		&i.ReplayedCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConsumerCheckpoint = `-- name: UpsertConsumerCheckpoint :one
INSERT INTO consumer_checkpoints (
    stream_name, consumer_group, consumer_name, last_redis_message_id,
    pending_count, last_error, heartbeat_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (stream_name, consumer_group, consumer_name)
DO UPDATE SET
    last_redis_message_id = EXCLUDED.last_redis_message_id,
    pending_count = EXCLUDED.pending_count,
    last_error = EXCLUDED.last_error,
    heartbeat_at = EXCLUDED.heartbeat_at,
    updated_at = NOW()
RETURNING id, stream_name, consumer_group, consumer_name, last_redis_message_id, pending_count, last_error, heartbeat_at, updated_at
`

type UpsertConsumerCheckpointParams struct {
	StreamName         string      `json:"stream_name"`
	ConsumerGroup      string      `json:"consumer_group"`
	ConsumerName       string      `json:"consumer_name"`
	LastRedisMessageID pgtype.Text `json:"last_redis_message_id"`
	PendingCount       int64       `json:"pending_count"`
	LastError          pgtype.Text `json:"last_error"`
	HeartbeatAt        time.Time   `json:"heartbeat_at"`
}

func (q *Queries) UpsertConsumerCheckpoint(ctx context.Context, arg UpsertConsumerCheckpointParams) (ConsumerCheckpoint, error) {
	row := q.db.QueryRow(ctx, upsertConsumerCheckpoint,
		arg.StreamName,
		arg.ConsumerGroup,
		arg.ConsumerName,
		arg.LastRedisMessageID,
		arg.PendingCount,
		arg.LastError,
		arg.HeartbeatAt,
	)
	var i ConsumerCheckpoint
	err := row.Scan(
		&i.ID,
		&i.StreamName,
		&i.ConsumerGroup,
		&i.ConsumerName,
		&i.LastRedisMessageID,
		&i.PendingCount,
		&i.LastError,
		&i.HeartbeatAt,
		&i.UpdatedAt,
	)
	return i, err
}
