// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extension_tokens.sql

package database

import (
	"context"
)

const createExtensionToken = `-- name: CreateExtensionToken :one
INSERT INTO extension_tokens (workspace_id, token, name)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, token, name, last_used_at, created_at
`

type CreateExtensionTokenParams struct {
	WorkspaceID string `json:"workspace_id"`
	Token       string `json:"token"`
	Name        string `json:"name"`
}

func (q *Queries) CreateExtensionToken(ctx context.Context, arg CreateExtensionTokenParams) (ExtensionToken, error) {
	row := q.db.QueryRow(ctx, createExtensionToken, arg.WorkspaceID, arg.Token, arg.Name)
	var i ExtensionToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Token,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExtensionTokenByWorkspace = `-- name: DeleteExtensionTokenByWorkspace :exec
DELETE FROM extension_tokens
WHERE workspace_id = $1
`

func (q *Queries) DeleteExtensionTokenByWorkspace(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, deleteExtensionTokenByWorkspace, workspaceID)
	return err
}

const getExtensionTokenByToken = `-- name: GetExtensionTokenByToken :one
SELECT id, workspace_id, token, name, last_used_at, created_at FROM extension_tokens
WHERE token = $1
`

func (q *Queries) GetExtensionTokenByToken(ctx context.Context, token string) (ExtensionToken, error) {
	row := q.db.QueryRow(ctx, getExtensionTokenByToken, token)
	var i ExtensionToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Token,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExtensionTokenByWorkspace = `-- name: GetExtensionTokenByWorkspace :one
SELECT id, workspace_id, token, name, last_used_at, created_at FROM extension_tokens
WHERE workspace_id = $1
`

func (q *Queries) GetExtensionTokenByWorkspace(ctx context.Context, workspaceID string) (ExtensionToken, error) {
	row := q.db.QueryRow(ctx, getExtensionTokenByWorkspace, workspaceID)
	var i ExtensionToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Token,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchExtensionToken = `-- name: TouchExtensionToken :exec
UPDATE extension_tokens
SET last_used_at = NOW()
WHERE token = $1
`

func (q *Queries) TouchExtensionToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, touchExtensionToken, token)
	return err
}
