// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keywords.sql

package database

import (
	"context"
	"time"
)

const countKeywords = `-- name: CountKeywords :one
SELECT COUNT(*)::int as count FROM keywords
WHERE workspace_id = $1
`

func (q *Queries) CountKeywords(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countKeywords, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createKeyword = `-- name: CreateKeyword :one
INSERT INTO keywords (
    workspace_id, term, platforms, is_active, match_type, negative_terms, subreddits
) VALUES (
    $1, $2, $3::platform_type[], $4, $5, $6, $7
) RETURNING id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
`

type CreateKeywordParams struct {
	WorkspaceID   string   `json:"workspace_id"`
	Term          string   `json:"term"`
	Platforms     []string `json:"platforms"`
	IsActive      bool     `json:"is_active"`
	MatchType     string   `json:"match_type"`
	NegativeTerms []string `json:"negative_terms"`
	Subreddits    []string `json:"subreddits"`
}

type CreateKeywordRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateKeyword(ctx context.Context, arg CreateKeywordParams) (CreateKeywordRow, error) {
	row := q.db.QueryRow(ctx, createKeyword,
		arg.WorkspaceID,
		arg.Term,
		arg.Platforms,
		arg.IsActive,
		arg.MatchType,
		arg.NegativeTerms,
		arg.Subreddits,
	)
	var i CreateKeywordRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Term,
		&i.Platforms,
		&i.IsActive,
		&i.MatchType,
		&i.NegativeTerms,
		&i.Subreddits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKeyword = `-- name: DeleteKeyword :exec
DELETE FROM keywords
WHERE id = $1 AND workspace_id = $2
`

type DeleteKeywordParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteKeyword(ctx context.Context, arg DeleteKeywordParams) error {
	_, err := q.db.Exec(ctx, deleteKeyword, arg.ID, arg.WorkspaceID)
	return err
}

const getKeyword = `-- name: GetKeyword :one
SELECT id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
FROM keywords
WHERE id = $1 AND workspace_id = $2
`

type GetKeywordParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetKeywordRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetKeyword(ctx context.Context, arg GetKeywordParams) (GetKeywordRow, error) {
	row := q.db.QueryRow(ctx, getKeyword, arg.ID, arg.WorkspaceID)
	var i GetKeywordRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Term,
		&i.Platforms,
		&i.IsActive,
		&i.MatchType,
		&i.NegativeTerms,
		&i.Subreddits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveKeywords = `-- name: ListActiveKeywords :many
SELECT id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
FROM keywords
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

type ListActiveKeywordsRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListActiveKeywords(ctx context.Context, workspaceID string) ([]ListActiveKeywordsRow, error) {
	rows, err := q.db.Query(ctx, listActiveKeywords, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveKeywordsRow{}
	for rows.Next() {
		var i ListActiveKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Term,
			&i.Platforms,
			&i.IsActive,
			&i.MatchType,
			&i.NegativeTerms,
			&i.Subreddits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveKeywords = `-- name: ListAllActiveKeywords :many
SELECT id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
FROM keywords
WHERE is_active = true
ORDER BY workspace_id, created_at DESC
`

type ListAllActiveKeywordsRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListAllActiveKeywords(ctx context.Context) ([]ListAllActiveKeywordsRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveKeywordsRow{}
	for rows.Next() {
		var i ListAllActiveKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Term,
			&i.Platforms,
			&i.IsActive,
			&i.MatchType,
			&i.NegativeTerms,
			&i.Subreddits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeywords = `-- name: ListKeywords :many
SELECT id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
FROM keywords
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListKeywordsRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListKeywords(ctx context.Context, workspaceID string) ([]ListKeywordsRow, error) {
	rows, err := q.db.Query(ctx, listKeywords, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeywordsRow{}
	for rows.Next() {
		var i ListKeywordsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Term,
			&i.Platforms,
			&i.IsActive,
			&i.MatchType,
			&i.NegativeTerms,
			&i.Subreddits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyword = `-- name: UpdateKeyword :one
UPDATE keywords
SET term = $1,
    platforms = $2::platform_type[],
    is_active = $3,
    match_type = $4,
    negative_terms = $5,
    subreddits = $6
WHERE id = $7 AND workspace_id = $8
RETURNING id, workspace_id, term,
    platforms::text[] as platforms,
    is_active, match_type, negative_terms, subreddits, created_at, updated_at
`

type UpdateKeywordParams struct {
	Term          string   `json:"term"`
	Platforms     []string `json:"platforms"`
	IsActive      bool     `json:"is_active"`
	MatchType     string   `json:"match_type"`
	NegativeTerms []string `json:"negative_terms"`
	Subreddits    []string `json:"subreddits"`
	ID            string   `json:"id"`
	WorkspaceID   string   `json:"workspace_id"`
}

type UpdateKeywordRow struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	Subreddits    []string  `json:"subreddits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpdateKeyword(ctx context.Context, arg UpdateKeywordParams) (UpdateKeywordRow, error) {
	row := q.db.QueryRow(ctx, updateKeyword,
		arg.Term,
		arg.Platforms,
		arg.IsActive,
		arg.MatchType,
		arg.NegativeTerms,
		arg.Subreddits,
		arg.ID,
		arg.WorkspaceID,
	)
	var i UpdateKeywordRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Term,
		&i.Platforms,
		&i.IsActive,
		&i.MatchType,
		&i.NegativeTerms,
		&i.Subreddits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
