// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leads.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeadsByStage = `-- name: CountLeadsByStage :many
SELECT stage, COUNT(*)::int as count
FROM leads
WHERE workspace_id = $1
GROUP BY stage
`

type CountLeadsByStageRow struct {
	Stage LeadStage `json:"stage"`
	Count int32     `json:"count"`
}

func (q *Queries) CountLeadsByStage(ctx context.Context, workspaceID string) ([]CountLeadsByStageRow, error) {
	rows, err := q.db.Query(ctx, countLeadsByStage, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLeadsByStageRow{}
	for rows.Next() {
		var i CountLeadsByStageRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (
    workspace_id, mention_id, stage,
    contact_name, contact_email, company,
    username, platform, profile_url,
    estimated_value, notes, tags, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13
) RETURNING id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at
`

type CreateLeadParams struct {
	WorkspaceID    string           `json:"workspace_id"`
	MentionID      pgtype.UUID      `json:"mention_id"`
	Stage          LeadStage        `json:"stage"`
	ContactName    pgtype.Text      `json:"contact_name"`
	ContactEmail   pgtype.Text      `json:"contact_email"`
	Company        pgtype.Text      `json:"company"`
	Username       pgtype.Text      `json:"username"`
	Platform       NullPlatformType `json:"platform"`
	ProfileUrl     pgtype.Text      `json:"profile_url"`
	EstimatedValue pgtype.Int4      `json:"estimated_value"`
	Notes          pgtype.Text      `json:"notes"`
	Tags           []string         `json:"tags"`
	Metadata       []byte           `json:"metadata"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.WorkspaceID,
		arg.MentionID,
		arg.Stage,
		arg.ContactName,
		arg.ContactEmail,
		arg.Company,
		arg.Username,
		arg.Platform,
		arg.ProfileUrl,
		arg.EstimatedValue,
		arg.Notes,
		arg.Tags,
		arg.Metadata,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MentionID,
		&i.Stage,
		&i.ContactName,
		&i.ContactEmail,
		&i.Company,
		&i.Username,
		&i.Platform,
		&i.ProfileUrl,
		&i.EstimatedValue,
		&i.Notes,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeadEvent = `-- name: CreateLeadEvent :one
INSERT INTO lead_events (
    lead_id, previous_stage, new_stage, changed_by, notes
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, lead_id, previous_stage, new_stage, changed_by, notes, created_at
`

type CreateLeadEventParams struct {
	LeadID        string        `json:"lead_id"`
	PreviousStage NullLeadStage `json:"previous_stage"`
	NewStage      LeadStage     `json:"new_stage"`
	ChangedBy     pgtype.UUID   `json:"changed_by"`
	Notes         pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateLeadEvent(ctx context.Context, arg CreateLeadEventParams) (LeadEvent, error) {
	row := q.db.QueryRow(ctx, createLeadEvent,
		arg.LeadID,
		arg.PreviousStage,
		arg.NewStage,
		arg.ChangedBy,
		arg.Notes,
	)
	var i LeadEvent
	err := row.Scan(
		&i.ID,
		&i.LeadID,
		&i.PreviousStage,
		&i.NewStage,
		&i.ChangedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at FROM leads
WHERE id = $1 AND workspace_id = $2
`

type GetLeadParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetLead(ctx context.Context, arg GetLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, arg.ID, arg.WorkspaceID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MentionID,
		&i.Stage,
		&i.ContactName,
		&i.ContactEmail,
		&i.Company,
		&i.Username,
		&i.Platform,
		&i.ProfileUrl,
		&i.EstimatedValue,
		&i.Notes,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeadEvents = `-- name: ListLeadEvents :many
SELECT id, lead_id, previous_stage, new_stage, changed_by, notes, created_at FROM lead_events
WHERE lead_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLeadEvents(ctx context.Context, leadID string) ([]LeadEvent, error) {
	rows, err := q.db.Query(ctx, listLeadEvents, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadEvent{}
	for rows.Next() {
		var i LeadEvent
		if err := rows.Scan(
			&i.ID,
			&i.LeadID,
			&i.PreviousStage,
			&i.NewStage,
			&i.ChangedBy,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeads = `-- name: ListLeads :many
SELECT id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at FROM leads
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListLeadsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MentionID,
			&i.Stage,
			&i.ContactName,
			&i.ContactEmail,
			&i.Company,
			&i.Username,
			&i.Platform,
			&i.ProfileUrl,
			&i.EstimatedValue,
			&i.Notes,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsByStage = `-- name: ListLeadsByStage :many
SELECT id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at FROM leads
WHERE workspace_id = $1 AND stage = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListLeadsByStageParams struct {
	WorkspaceID string    `json:"workspace_id"`
	Stage       LeadStage `json:"stage"`
	Off         int32     `json:"off"`
	Lim         int32     `json:"lim"`
}

func (q *Queries) ListLeadsByStage(ctx context.Context, arg ListLeadsByStageParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsByStage,
		arg.WorkspaceID,
		arg.Stage,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.MentionID,
			&i.Stage,
			&i.ContactName,
			&i.ContactEmail,
			&i.Company,
			&i.Username,
			&i.Platform,
			&i.ProfileUrl,
			&i.EstimatedValue,
			&i.Notes,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLead = `-- name: UpdateLead :one
UPDATE leads
SET
    stage = COALESCE($1, stage),
    contact_name = COALESCE($2, contact_name),
    contact_email = COALESCE($3, contact_email),
    company = COALESCE($4, company),
    notes = COALESCE($5, notes),
    estimated_value = COALESCE($6, estimated_value)
WHERE id = $7 AND workspace_id = $8
RETURNING id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at
`

type UpdateLeadParams struct {
	Stage          LeadStage   `json:"stage"`
	ContactName    pgtype.Text `json:"contact_name"`
	ContactEmail   pgtype.Text `json:"contact_email"`
	Company        pgtype.Text `json:"company"`
	Notes          pgtype.Text `json:"notes"`
	EstimatedValue pgtype.Int4 `json:"estimated_value"`
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLead,
		arg.Stage,
		arg.ContactName,
		arg.ContactEmail,
		arg.Company,
		arg.Notes,
		arg.EstimatedValue,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MentionID,
		&i.Stage,
		&i.ContactName,
		&i.ContactEmail,
		&i.Company,
		&i.Username,
		&i.Platform,
		&i.ProfileUrl,
		&i.EstimatedValue,
		&i.Notes,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeadStage = `-- name: UpdateLeadStage :one
UPDATE leads
SET stage = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, mention_id, stage, contact_name, contact_email, company, username, platform, profile_url, estimated_value, notes, tags, metadata, created_at, updated_at
`

type UpdateLeadStageParams struct {
	Stage       LeadStage `json:"stage"`
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
}

func (q *Queries) UpdateLeadStage(ctx context.Context, arg UpdateLeadStageParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStage, arg.Stage, arg.ID, arg.WorkspaceID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.MentionID,
		&i.Stage,
		&i.ContactName,
		&i.ContactEmail,
		&i.Company,
		&i.Username,
		&i.Platform,
		&i.ProfileUrl,
		&i.EstimatedValue,
		&i.Notes,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
