// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const assignMention = `-- name: AssignMention :one
UPDATE mentions
SET assigned_to = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level
`

type AssignMentionParams struct {
	AssignedTo  pgtype.UUID `json:"assigned_to"`
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) AssignMention(ctx context.Context, arg AssignMentionParams) (Mention, error) {
	row := q.db.QueryRow(ctx, assignMention, arg.AssignedTo, arg.ID, arg.WorkspaceID)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}

const countMentionsByPlatform = `-- name: CountMentionsByPlatform :many
SELECT platform, COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
GROUP BY platform
`

type CountMentionsByPlatformRow struct {
	Platform string `json:"platform"`
	Count    int32  `json:"count"`
}

func (q *Queries) CountMentionsByPlatform(ctx context.Context, workspaceID string) ([]CountMentionsByPlatformRow, error) {
	rows, err := q.db.Query(ctx, countMentionsByPlatform, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMentionsByPlatformRow{}
	for rows.Next() {
		var i CountMentionsByPlatformRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMentionsByStatus = `-- name: CountMentionsByStatus :many
SELECT status, COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
GROUP BY status
`

type CountMentionsByStatusRow struct {
	Status MentionStatus `json:"status"`
	Count  int32         `json:"count"`
}

func (q *Queries) CountMentionsByStatus(ctx context.Context, workspaceID string) ([]CountMentionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countMentionsByStatus, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMentionsByStatusRow{}
	for rows.Next() {
		var i CountMentionsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMentionsByTier = `-- name: CountMentionsByTier :many
SELECT
    CASE
        WHEN relevance_score >= 7.0 AND intent IN ('buy_signal', 'recommendation_ask', 'complaint') THEN 'leads_ready'
        WHEN relevance_score >= 4.0 AND relevance_score < 7.0 THEN 'worth_watching'
        ELSE 'filtered'
    END as tier,
    COUNT(*)::int as count
FROM mentions
WHERE workspace_id = $1
GROUP BY tier
`

type CountMentionsByTierRow struct {
	Tier  string `json:"tier"`
	Count int32  `json:"count"`
}

func (q *Queries) CountMentionsByTier(ctx context.Context, workspaceID string) ([]CountMentionsByTierRow, error) {
	rows, err := q.db.Query(ctx, countMentionsByTier, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMentionsByTierRow{}
	for rows.Next() {
		var i CountMentionsByTierRow
		if err := rows.Scan(&i.Tier, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMention = `-- name: CreateMention :one
INSERT INTO mentions (
    workspace_id, keyword_id, platform, platform_id, url,
    title, content, author_username, author_profile_url,
    author_karma, author_account_age_days,
    relevance_score, intent, conversion_probability, status,
    platform_metadata, engagement_metrics, keyword_matches,
    platform_created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18,
    $19
) RETURNING id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level
`

type CreateMentionParams struct {
	WorkspaceID           string             `json:"workspace_id"`
	KeywordID             pgtype.UUID        `json:"keyword_id"`
	Platform              string             `json:"platform"`
	PlatformID            string             `json:"platform_id"`
	Url                   string             `json:"url"`
	Title                 pgtype.Text        `json:"title"`
	Content               string             `json:"content"`
	AuthorUsername        pgtype.Text        `json:"author_username"`
	AuthorProfileUrl      pgtype.Text        `json:"author_profile_url"`
	AuthorKarma           pgtype.Int4        `json:"author_karma"`
	AuthorAccountAgeDays  pgtype.Int4        `json:"author_account_age_days"`
	RelevanceScore        pgtype.Float4      `json:"relevance_score"`
	Intent                NullIntentType     `json:"intent"`
	ConversionProbability pgtype.Float4      `json:"conversion_probability"`
	Status                MentionStatus      `json:"status"`
	PlatformMetadata      []byte             `json:"platform_metadata"`
	EngagementMetrics     []byte             `json:"engagement_metrics"`
	KeywordMatches        []string           `json:"keyword_matches"`
	PlatformCreatedAt     pgtype.Timestamptz `json:"platform_created_at"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRow(ctx, createMention,
		arg.WorkspaceID,
		arg.KeywordID,
		arg.Platform,
		arg.PlatformID,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.AuthorUsername,
		arg.AuthorProfileUrl,
		arg.AuthorKarma,
		arg.AuthorAccountAgeDays,
		arg.RelevanceScore,
		arg.Intent,
		arg.ConversionProbability,
		arg.Status,
		arg.PlatformMetadata,
		arg.EngagementMetrics,
		arg.KeywordMatches,
		arg.PlatformCreatedAt,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}

const getMention = `-- name: GetMention :one
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE id = $1 AND workspace_id = $2
`

type GetMentionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMention(ctx context.Context, arg GetMentionParams) (Mention, error) {
	row := q.db.QueryRow(ctx, getMention, arg.ID, arg.WorkspaceID)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}

const listMentions = `-- name: ListMentions :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMentionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListMentions(ctx context.Context, arg ListMentionsParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentions, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByIntent = `-- name: ListMentionsByIntent :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1 AND intent = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListMentionsByIntentParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Intent      NullIntentType `json:"intent"`
	Off         int32          `json:"off"`
	Lim         int32          `json:"lim"`
}

func (q *Queries) ListMentionsByIntent(ctx context.Context, arg ListMentionsByIntentParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsByIntent,
		arg.WorkspaceID,
		arg.Intent,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByPlatform = `-- name: ListMentionsByPlatform :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1 AND platform = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListMentionsByPlatformParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListMentionsByPlatform(ctx context.Context, arg ListMentionsByPlatformParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsByPlatform,
		arg.WorkspaceID,
		arg.Platform,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByStatus = `-- name: ListMentionsByStatus :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListMentionsByStatusParams struct {
	WorkspaceID string        `json:"workspace_id"`
	Status      MentionStatus `json:"status"`
	Off         int32         `json:"off"`
	Lim         int32         `json:"lim"`
}

func (q *Queries) ListMentionsByStatus(ctx context.Context, arg ListMentionsByStatusParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsByStatus,
		arg.WorkspaceID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsFiltered = `-- name: ListMentionsFiltered :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1
AND (relevance_score IS NULL OR relevance_score < 4.0)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMentionsFilteredParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListMentionsFiltered(ctx context.Context, arg ListMentionsFilteredParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsFiltered, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsLeadsReady = `-- name: ListMentionsLeadsReady :many

SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1
AND relevance_score >= 7.0
AND intent IN ('buy_signal', 'recommendation_ask', 'complaint')
ORDER BY relevance_score DESC, created_at DESC
LIMIT $3 OFFSET $2
`

type ListMentionsLeadsReadyParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

// ─── Smart Inbox Tiers ────────────────────────────────
func (q *Queries) ListMentionsLeadsReady(ctx context.Context, arg ListMentionsLeadsReadyParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsLeadsReady, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsWorthWatching = `-- name: ListMentionsWorthWatching :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1
AND relevance_score IS NOT NULL
AND relevance_score >= 4.0
AND relevance_score < 7.0
ORDER BY relevance_score DESC, created_at DESC
LIMIT $3 OFFSET $2
`

type ListMentionsWorthWatchingParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListMentionsWorthWatching(ctx context.Context, arg ListMentionsWorthWatchingParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listMentionsWorthWatching, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLeadsForWorkspace = `-- name: ListRecentLeadsForWorkspace :many
SELECT id, platform, url, title, content, author_username,
       intent, relevance_score, created_at
FROM mentions
WHERE workspace_id = $1
  AND (
    (relevance_score >= 7.0 AND intent IN ('buy_signal', 'recommendation_ask', 'complaint'))
    OR (relevance_score >= 4.0 AND relevance_score < 7.0)
  )
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentLeadsForWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Lim         int32  `json:"lim"`
}

type ListRecentLeadsForWorkspaceRow struct {
	ID             string         `json:"id"`
	Platform       string         `json:"platform"`
	Url            string         `json:"url"`
	Title          pgtype.Text    `json:"title"`
	Content        string         `json:"content"`
	AuthorUsername pgtype.Text    `json:"author_username"`
	Intent         NullIntentType `json:"intent"`
	RelevanceScore pgtype.Float4  `json:"relevance_score"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) ListRecentLeadsForWorkspace(ctx context.Context, arg ListRecentLeadsForWorkspaceParams) ([]ListRecentLeadsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listRecentLeadsForWorkspace, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentLeadsForWorkspaceRow{}
	for rows.Next() {
		var i ListRecentLeadsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.AuthorUsername,
			&i.Intent,
			&i.RelevanceScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclassifiedMentions = `-- name: ListUnclassifiedMentions :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1 AND intent IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListUnclassifiedMentionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListUnclassifiedMentions(ctx context.Context, arg ListUnclassifiedMentionsParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, listUnclassifiedMentions, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentions = `-- name: SearchMentions :many
SELECT id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level FROM mentions
WHERE workspace_id = $1
AND content_tsv @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(content_tsv, plainto_tsquery('english', $2)) DESC
LIMIT $4 OFFSET $3
`

type SearchMentionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Query       string `json:"query"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) SearchMentions(ctx context.Context, arg SearchMentionsParams) ([]Mention, error) {
	rows, err := q.db.Query(ctx, searchMentions,
		arg.WorkspaceID,
		arg.Query,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.KeywordID,
			&i.Platform,
			&i.PlatformID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.ContentTsv,
			&i.AuthorUsername,
			&i.AuthorProfileUrl,
			&i.AuthorKarma,
			&i.AuthorAccountAgeDays,
			&i.RelevanceScore,
			&i.Intent,
			&i.ConversionProbability,
			&i.Status,
			&i.AssignedTo,
			&i.PlatformMetadata,
			&i.EngagementMetrics,
			&i.KeywordMatches,
			&i.PlatformCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentEmbedding,
			&i.ScoringMetadata,
			&i.AwarenessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMentionAwarenessLevel = `-- name: UpdateMentionAwarenessLevel :exec
UPDATE mentions
SET awareness_level = $1
WHERE id = $2 AND workspace_id = $3
`

type UpdateMentionAwarenessLevelParams struct {
	AwarenessLevel pgtype.Text `json:"awareness_level"`
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
}

func (q *Queries) UpdateMentionAwarenessLevel(ctx context.Context, arg UpdateMentionAwarenessLevelParams) error {
	_, err := q.db.Exec(ctx, updateMentionAwarenessLevel, arg.AwarenessLevel, arg.ID, arg.WorkspaceID)
	return err
}

const updateMentionEmbedding = `-- name: UpdateMentionEmbedding :exec

UPDATE mentions
SET content_embedding = $1
WHERE id = $2
`

type UpdateMentionEmbeddingParams struct {
	ContentEmbedding pgvector.Vector `json:"content_embedding"`
	ID               string          `json:"id"`
}

// ─── Embedding & Scoring ──────────────────────────────
func (q *Queries) UpdateMentionEmbedding(ctx context.Context, arg UpdateMentionEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateMentionEmbedding, arg.ContentEmbedding, arg.ID)
	return err
}

const updateMentionIntent = `-- name: UpdateMentionIntent :one
UPDATE mentions
SET intent = $1,
    conversion_probability = $2,
    relevance_score = $3
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level
`

type UpdateMentionIntentParams struct {
	Intent                NullIntentType `json:"intent"`
	ConversionProbability pgtype.Float4  `json:"conversion_probability"`
	RelevanceScore        pgtype.Float4  `json:"relevance_score"`
	ID                    string         `json:"id"`
	WorkspaceID           string         `json:"workspace_id"`
}

func (q *Queries) UpdateMentionIntent(ctx context.Context, arg UpdateMentionIntentParams) (Mention, error) {
	row := q.db.QueryRow(ctx, updateMentionIntent,
		arg.Intent,
		arg.ConversionProbability,
		arg.RelevanceScore,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}

const updateMentionScoring = `-- name: UpdateMentionScoring :one
UPDATE mentions
SET intent = $1,
    conversion_probability = $2,
    relevance_score = $3,
    scoring_metadata = $4,
    awareness_level = $5
WHERE id = $6 AND workspace_id = $7
RETURNING id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level
`

type UpdateMentionScoringParams struct {
	Intent                NullIntentType `json:"intent"`
	ConversionProbability pgtype.Float4  `json:"conversion_probability"`
	RelevanceScore        pgtype.Float4  `json:"relevance_score"`
	ScoringMetadata       []byte         `json:"scoring_metadata"`
	AwarenessLevel        pgtype.Text    `json:"awareness_level"`
	ID                    string         `json:"id"`
	WorkspaceID           string         `json:"workspace_id"`
}

func (q *Queries) UpdateMentionScoring(ctx context.Context, arg UpdateMentionScoringParams) (Mention, error) {
	row := q.db.QueryRow(ctx, updateMentionScoring,
		arg.Intent,
		arg.ConversionProbability,
		arg.RelevanceScore,
		arg.ScoringMetadata,
		arg.AwarenessLevel,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}

const updateMentionStatus = `-- name: UpdateMentionStatus :one
UPDATE mentions
SET status = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, keyword_id, platform, platform_id, url, title, content, content_tsv, author_username, author_profile_url, author_karma, author_account_age_days, relevance_score, intent, conversion_probability, status, assigned_to, platform_metadata, engagement_metrics, keyword_matches, platform_created_at, created_at, updated_at, content_embedding, scoring_metadata, awareness_level
`

type UpdateMentionStatusParams struct {
	Status      MentionStatus `json:"status"`
	ID          string        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
}

func (q *Queries) UpdateMentionStatus(ctx context.Context, arg UpdateMentionStatusParams) (Mention, error) {
	row := q.db.QueryRow(ctx, updateMentionStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.KeywordID,
		&i.Platform,
		&i.PlatformID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.ContentTsv,
		&i.AuthorUsername,
		&i.AuthorProfileUrl,
		&i.AuthorKarma,
		&i.AuthorAccountAgeDays,
		&i.RelevanceScore,
		&i.Intent,
		&i.ConversionProbability,
		&i.Status,
		&i.AssignedTo,
		&i.PlatformMetadata,
		&i.EngagementMetrics,
		&i.KeywordMatches,
		&i.PlatformCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentEmbedding,
		&i.ScoringMetadata,
		&i.AwarenessLevel,
	)
	return i, err
}
