// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type ExecutionStatus string

const (
	ExecutionStatusRunning         ExecutionStatus = "running"
	ExecutionStatusWaitingApproval ExecutionStatus = "waiting_approval"
	ExecutionStatusCompleted       ExecutionStatus = "completed"
	ExecutionStatusFailed          ExecutionStatus = "failed"
	ExecutionStatusExpired         ExecutionStatus = "expired"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus `json:"execution_status"`
	Valid           bool            `json:"valid"` // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type IntentType string

const (
	IntentTypeBuySignal         IntentType = "buy_signal"
	IntentTypeComplaint         IntentType = "complaint"
	IntentTypeRecommendationAsk IntentType = "recommendation_ask"
	IntentTypeComparison        IntentType = "comparison"
	IntentTypeGeneral           IntentType = "general"
)

func (e *IntentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntentType(s)
	case string:
		*e = IntentType(s)
	default:
		return fmt.Errorf("unsupported scan type for IntentType: %T", src)
	}
	return nil
}

type NullIntentType struct {
	IntentType IntentType `json:"intent_type"`
	Valid      bool       `json:"valid"` // Valid is true if IntentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntentType) Scan(value interface{}) error {
	if value == nil {
		ns.IntentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntentType), nil
}

type LeadStage string

const (
	LeadStageProspect  LeadStage = "prospect"
	LeadStageQualified LeadStage = "qualified"
	LeadStageEngaged   LeadStage = "engaged"
	LeadStageConverted LeadStage = "converted"
	LeadStageLost      LeadStage = "lost"
)

func (e *LeadStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadStage(s)
	case string:
		*e = LeadStage(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadStage: %T", src)
	}
	return nil
}

type NullLeadStage struct {
	LeadStage LeadStage `json:"lead_stage"`
	Valid     bool      `json:"valid"` // Valid is true if LeadStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadStage) Scan(value interface{}) error {
	if value == nil {
		ns.LeadStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadStage), nil
}

type MentionStatus string

const (
	MentionStatusNew      MentionStatus = "new"
	MentionStatusReviewed MentionStatus = "reviewed"
	MentionStatusReplied  MentionStatus = "replied"
	MentionStatusArchived MentionStatus = "archived"
	MentionStatusSpam     MentionStatus = "spam"
)

func (e *MentionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MentionStatus(s)
	case string:
		*e = MentionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MentionStatus: %T", src)
	}
	return nil
}

type NullMentionStatus struct {
	MentionStatus MentionStatus `json:"mention_status"`
	Valid         bool          `json:"valid"` // Valid is true if MentionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMentionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MentionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MentionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMentionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MentionStatus), nil
}

type NotificationChannel string

const (
	NotificationChannelSlack   NotificationChannel = "slack"
	NotificationChannelDiscord NotificationChannel = "discord"
	NotificationChannelEmail   NotificationChannel = "email"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type PlatformType string

const (
	PlatformTypeHackernews   PlatformType = "hackernews"
	PlatformTypeReddit       PlatformType = "reddit"
	PlatformTypeTwitter      PlatformType = "twitter"
	PlatformTypeLinkedin     PlatformType = "linkedin"
	PlatformTypeDevto        PlatformType = "devto"
	PlatformTypeLobsters     PlatformType = "lobsters"
	PlatformTypeIndiehackers PlatformType = "indiehackers"
)

func (e *PlatformType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformType(s)
	case string:
		*e = PlatformType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformType: %T", src)
	}
	return nil
}

type NullPlatformType struct {
	PlatformType PlatformType `json:"platform_type"`
	Valid        bool         `json:"valid"` // Valid is true if PlatformType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformType) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformType), nil
}

type ReplyStatus string

const (
	ReplyStatusDraft    ReplyStatus = "draft"
	ReplyStatusApproved ReplyStatus = "approved"
	ReplyStatusPosted   ReplyStatus = "posted"
	ReplyStatusFailed   ReplyStatus = "failed"
)

func (e *ReplyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReplyStatus(s)
	case string:
		*e = ReplyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReplyStatus: %T", src)
	}
	return nil
}

type NullReplyStatus struct {
	ReplyStatus ReplyStatus `json:"reply_status"`
	Valid       bool        `json:"valid"` // Valid is true if ReplyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReplyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReplyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReplyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReplyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReplyStatus), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
	UserRoleViewer UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WorkflowStatus string

const (
	WorkflowStatusActive   WorkflowStatus = "active"
	WorkflowStatusPaused   WorkflowStatus = "paused"
	WorkflowStatusDisabled WorkflowStatus = "disabled"
)

func (e *WorkflowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowStatus(s)
	case string:
		*e = WorkflowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowStatus: %T", src)
	}
	return nil
}

type NullWorkflowStatus struct {
	WorkflowStatus WorkflowStatus `json:"workflow_status"`
	Valid          bool           `json:"valid"` // Valid is true if WorkflowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowStatus), nil
}

type Document struct {
	ID            string      `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	ContentType   string      `json:"content_type"`
	SourceUrl     pgtype.Text `json:"source_url"`
	FileSizeBytes pgtype.Int4 `json:"file_size_bytes"`
	ChunkCount    int32       `json:"chunk_count"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type DocumentChunk struct {
	ID           string              `json:"id"`
	DocumentID   string              `json:"document_id"`
	WorkspaceID  string              `json:"workspace_id"`
	Content      string              `json:"content"`
	ContentTsv   interface{}         `json:"content_tsv"`
	Embedding    *pgvector_go.Vector `json:"embedding"`
	ChunkIndex   int32               `json:"chunk_index"`
	SectionTitle pgtype.Text         `json:"section_title"`
	Metadata     []byte              `json:"metadata"`
	TokenCount   pgtype.Int4         `json:"token_count"`
	CreatedAt    time.Time           `json:"created_at"`
}

type ExtensionToken struct {
	ID          string             `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Token       string             `json:"token"`
	Name        string             `json:"name"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Keyword struct {
	ID            string    `json:"id"`
	WorkspaceID   string    `json:"workspace_id"`
	Term          string    `json:"term"`
	Platforms     []string  `json:"platforms"`
	IsActive      bool      `json:"is_active"`
	MatchType     string    `json:"match_type"`
	NegativeTerms []string  `json:"negative_terms"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Subreddits    []string  `json:"subreddits"`
}

type Lead struct {
	ID             string           `json:"id"`
	WorkspaceID    string           `json:"workspace_id"`
	MentionID      pgtype.UUID      `json:"mention_id"`
	Stage          LeadStage        `json:"stage"`
	ContactName    pgtype.Text      `json:"contact_name"`
	ContactEmail   pgtype.Text      `json:"contact_email"`
	Company        pgtype.Text      `json:"company"`
	Username       pgtype.Text      `json:"username"`
	Platform       NullPlatformType `json:"platform"`
	ProfileUrl     pgtype.Text      `json:"profile_url"`
	EstimatedValue pgtype.Int4      `json:"estimated_value"`
	Notes          pgtype.Text      `json:"notes"`
	Tags           []string         `json:"tags"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type LeadEvent struct {
	ID            string        `json:"id"`
	LeadID        string        `json:"lead_id"`
	PreviousStage NullLeadStage `json:"previous_stage"`
	NewStage      LeadStage     `json:"new_stage"`
	ChangedBy     pgtype.UUID   `json:"changed_by"`
	Notes         pgtype.Text   `json:"notes"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Mention struct {
	ID                    string             `json:"id"`
	WorkspaceID           string             `json:"workspace_id"`
	KeywordID             pgtype.UUID        `json:"keyword_id"`
	Platform              string             `json:"platform"`
	PlatformID            string             `json:"platform_id"`
	Url                   string             `json:"url"`
	Title                 pgtype.Text        `json:"title"`
	Content               string             `json:"content"`
	ContentTsv            interface{}        `json:"content_tsv"`
	AuthorUsername        pgtype.Text        `json:"author_username"`
	AuthorProfileUrl      pgtype.Text        `json:"author_profile_url"`
	AuthorKarma           pgtype.Int4        `json:"author_karma"`
	AuthorAccountAgeDays  pgtype.Int4        `json:"author_account_age_days"`
	RelevanceScore        pgtype.Float4      `json:"relevance_score"`
	Intent                NullIntentType     `json:"intent"`
	ConversionProbability pgtype.Float4      `json:"conversion_probability"`
	Status                MentionStatus      `json:"status"`
	AssignedTo            pgtype.UUID        `json:"assigned_to"`
	PlatformMetadata      []byte             `json:"platform_metadata"`
	EngagementMetrics     []byte             `json:"engagement_metrics"`
	KeywordMatches        []string           `json:"keyword_matches"`
	PlatformCreatedAt     pgtype.Timestamptz `json:"platform_created_at"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	ContentEmbedding      pgvector.Vector    `json:"content_embedding"`
	ScoringMetadata       []byte             `json:"scoring_metadata"`
	AwarenessLevel        pgtype.Text        `json:"awareness_level"`
}

type MonitoringProfile struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Notification struct {
	ID          string              `json:"id"`
	WorkspaceID string              `json:"workspace_id"`
	Channel     NotificationChannel `json:"channel"`
	Recipient   string              `json:"recipient"`
	Subject     pgtype.Text         `json:"subject"`
	Body        string              `json:"body"`
	Metadata    []byte              `json:"metadata"`
	SentAt      pgtype.Timestamptz  `json:"sent_at"`
	Error       pgtype.Text         `json:"error"`
	CreatedAt   time.Time           `json:"created_at"`
}

type OnboardingAnalysis struct {
	ID           string      `json:"id"`
	WorkspaceID  string      `json:"workspace_id"`
	SourceUrl    string      `json:"source_url"`
	RawText      pgtype.Text `json:"raw_text"`
	Analysis     []byte      `json:"analysis"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

type PainPointEmbedding struct {
	ID          string              `json:"id"`
	ProfileID   string              `json:"profile_id"`
	WorkspaceID string              `json:"workspace_id"`
	Phrase      string              `json:"phrase"`
	Embedding   *pgvector_go.Vector `json:"embedding"`
	CreatedAt   time.Time           `json:"created_at"`
}

type PlatformAccount struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	UserID          string             `json:"user_id"`
	Platform        string             `json:"platform"`
	Username        pgtype.Text        `json:"username"`
	PlatformUserID  pgtype.Text        `json:"platform_user_id"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	Karma           pgtype.Int4        `json:"karma"`
	AccountAgeDays  pgtype.Int4        `json:"account_age_days"`
	TrustScore      pgtype.Float4      `json:"trust_score"`
	IsActive        bool               `json:"is_active"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Reply struct {
	ID                string             `json:"id"`
	MentionID         string             `json:"mention_id"`
	WorkspaceID       string             `json:"workspace_id"`
	Content           string             `json:"content"`
	EditedContent     pgtype.Text        `json:"edited_content"`
	Status            ReplyStatus        `json:"status"`
	PlatformPostID    pgtype.Text        `json:"platform_post_id"`
	PostedBy          pgtype.UUID        `json:"posted_by"`
	ApprovedBy        pgtype.UUID        `json:"approved_by"`
	UtmLinkID         pgtype.UUID        `json:"utm_link_id"`
	SafeLinkScore     pgtype.Float4      `json:"safe_link_score"`
	SafeLinkFlags     []byte             `json:"safe_link_flags"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	TemplateStyle     pgtype.Text        `json:"template_style"`
	ThreadContextUsed bool               `json:"thread_context_used"`
}

type ReplyEngagement struct {
	ID          string    `json:"id"`
	ReplyID     string    `json:"reply_id"`
	WorkspaceID string    `json:"workspace_id"`
	Upvotes     int32     `json:"upvotes"`
	Downvotes   int32     `json:"downvotes"`
	ReplyCount  int32     `json:"reply_count"`
	IsRemoved   bool      `json:"is_removed"`
	CheckedAt   time.Time `json:"checked_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type Subscription struct {
	ID                   string             `json:"id"`
	WorkspaceID          string             `json:"workspace_id"`
	PlanID               string             `json:"plan_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAt             pgtype.Timestamptz `json:"cancel_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type SubscriptionPlan struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	StripePriceID pgtype.Text `json:"stripe_price_id"`
	PriceCents    int32       `json:"price_cents"`
	KeywordLimit  int32       `json:"keyword_limit"`
	MentionLimit  int32       `json:"mention_limit"`
	SeatLimit     int32       `json:"seat_limit"`
	Features      []byte      `json:"features"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Thread struct {
	ID                  string      `json:"id"`
	MentionID           string      `json:"mention_id"`
	Platform            string      `json:"platform"`
	ThreadID            string      `json:"thread_id"`
	Content             []byte      `json:"content"`
	Summary             pgtype.Text `json:"summary"`
	Sentiment           pgtype.Text `json:"sentiment"`
	SolutionsMentioned  []string    `json:"solutions_mentioned"`
	OurProductMentioned bool        `json:"our_product_mentioned"`
	FetchedAt           time.Time   `json:"fetched_at"`
	CreatedAt           time.Time   `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	ClerkUserID  string             `json:"clerk_user_id"`
	WorkspaceID  string             `json:"workspace_id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Role         UserRole           `json:"role"`
	IsActive     bool               `json:"is_active"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}

type UtmEvent struct {
	ID           string      `json:"id"`
	UtmLinkID    string      `json:"utm_link_id"`
	EventType    string      `json:"event_type"`
	Referrer     pgtype.Text `json:"referrer"`
	UserAgent    pgtype.Text `json:"user_agent"`
	IpHash       pgtype.Text `json:"ip_hash"`
	RevenueCents pgtype.Int4 `json:"revenue_cents"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type UtmLink struct {
	ID             string      `json:"id"`
	WorkspaceID    string      `json:"workspace_id"`
	Code           string      `json:"code"`
	DestinationUrl string      `json:"destination_url"`
	UtmSource      string      `json:"utm_source"`
	UtmMedium      string      `json:"utm_medium"`
	UtmCampaign    pgtype.Text `json:"utm_campaign"`
	UtmContent     pgtype.Text `json:"utm_content"`
	ClickCount     int32       `json:"click_count"`
	SignupCount    int32       `json:"signup_count"`
	RevenueCents   int32       `json:"revenue_cents"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Workflow struct {
	ID                 string             `json:"id"`
	WorkspaceID        string             `json:"workspace_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Status             WorkflowStatus     `json:"status"`
	TriggerConfig      []byte             `json:"trigger_config"`
	ActionChain        []byte             `json:"action_chain"`
	MaxTriggersPerHour int32              `json:"max_triggers_per_hour"`
	ExecutionCount     int32              `json:"execution_count"`
	LastTriggeredAt    pgtype.Timestamptz `json:"last_triggered_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type WorkflowExecution struct {
	ID           string             `json:"id"`
	WorkflowID   string             `json:"workflow_id"`
	MentionID    pgtype.UUID        `json:"mention_id"`
	Status       ExecutionStatus    `json:"status"`
	Steps        []byte             `json:"steps"`
	CurrentStep  int32              `json:"current_step"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    time.Time          `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type Workspace struct {
	ID               string      `json:"id"`
	ClerkOrgID       string      `json:"clerk_org_id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	Tier             string      `json:"tier"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	Settings         []byte      `json:"settings"`
	KeywordLimit     int32       `json:"keyword_limit"`
	MentionLimit     int32       `json:"mention_limit"`
	SeatLimit        int32       `json:"seat_limit"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}
