// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)::int as count FROM notifications
WHERE workspace_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNotifications, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    workspace_id, channel, recipient, subject, body, metadata, sent_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, workspace_id, channel, recipient, subject, body, metadata, sent_at, error, created_at
`

type CreateNotificationParams struct {
	WorkspaceID string              `json:"workspace_id"`
	Channel     NotificationChannel `json:"channel"`
	Recipient   string              `json:"recipient"`
	Subject     pgtype.Text         `json:"subject"`
	Body        string              `json:"body"`
	Metadata    []byte              `json:"metadata"`
	SentAt      pgtype.Timestamptz  `json:"sent_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.WorkspaceID,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Metadata,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Body,
		&i.Metadata,
		&i.SentAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, workspace_id, channel, recipient, subject, body, metadata, sent_at, error, created_at FROM notifications
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.WorkspaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Metadata,
			&i.SentAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
