// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_analyses.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingAnalysis = `-- name: CreateOnboardingAnalysis :one
INSERT INTO onboarding_analyses (
    workspace_id, source_url, raw_text, analysis, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workspace_id, source_url, raw_text, analysis, status, error_message, created_at
`

type CreateOnboardingAnalysisParams struct {
	WorkspaceID string      `json:"workspace_id"`
	SourceUrl   string      `json:"source_url"`
	RawText     pgtype.Text `json:"raw_text"`
	Analysis    []byte      `json:"analysis"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateOnboardingAnalysis(ctx context.Context, arg CreateOnboardingAnalysisParams) (OnboardingAnalysis, error) {
	row := q.db.QueryRow(ctx, createOnboardingAnalysis,
		arg.WorkspaceID,
		arg.SourceUrl,
		arg.RawText,
		arg.Analysis,
		arg.Status,
	)
	var i OnboardingAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceUrl,
		&i.RawText,
		&i.Analysis,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOnboardingAnalysis = `-- name: GetLatestOnboardingAnalysis :one
SELECT id, workspace_id, source_url, raw_text, analysis, status, error_message, created_at FROM onboarding_analyses
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOnboardingAnalysis(ctx context.Context, workspaceID string) (OnboardingAnalysis, error) {
	row := q.db.QueryRow(ctx, getLatestOnboardingAnalysis, workspaceID)
	var i OnboardingAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceUrl,
		&i.RawText,
		&i.Analysis,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const updateOnboardingAnalysis = `-- name: UpdateOnboardingAnalysis :one
UPDATE onboarding_analyses
SET analysis = $1, status = $2, error_message = $3
WHERE id = $4
RETURNING id, workspace_id, source_url, raw_text, analysis, status, error_message, created_at
`

type UpdateOnboardingAnalysisParams struct {
	Analysis     []byte      `json:"analysis"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           string      `json:"id"`
}

func (q *Queries) UpdateOnboardingAnalysis(ctx context.Context, arg UpdateOnboardingAnalysisParams) (OnboardingAnalysis, error) {
	row := q.db.QueryRow(ctx, updateOnboardingAnalysis,
		arg.Analysis,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
	)
	var i OnboardingAnalysis
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceUrl,
		&i.RawText,
		&i.Analysis,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
