// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    workspace_id, display_name, bio, company, location, icp_fit_score, confidence, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, workspace_id, display_name, bio, company, location, icp_fit_score, confidence, metadata, created_at, updated_at
`

type CreatePersonParams struct {
	WorkspaceID string        `json:"workspace_id"`
	DisplayName pgtype.Text   `json:"display_name"`
	Bio         pgtype.Text   `json:"bio"`
	Company     pgtype.Text   `json:"company"`
	Location    pgtype.Text   `json:"location"`
	IcpFitScore pgtype.Float4 `json:"icp_fit_score"`
	Confidence  float32       `json:"confidence"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.WorkspaceID,
		arg.DisplayName,
		arg.Bio,
		arg.Company,
		arg.Location,
		arg.IcpFitScore,
		arg.Confidence,
		arg.Metadata,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.Bio,
		&i.Company,
		&i.Location,
		&i.IcpFitScore,
		&i.Confidence,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, workspace_id, display_name, bio, company, location, icp_fit_score, confidence, metadata, created_at, updated_at FROM persons
WHERE id = $1 AND workspace_id = $2
`

type GetPersonParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetPerson(ctx context.Context, arg GetPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, arg.ID, arg.WorkspaceID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.Bio,
		&i.Company,
		&i.Location,
		&i.IcpFitScore,
		&i.Confidence,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonByLead = `-- name: GetPersonByLead :one
SELECT p.id, p.workspace_id, p.display_name, p.bio, p.company, p.location, p.icp_fit_score, p.confidence, p.metadata, p.created_at, p.updated_at FROM persons p
JOIN leads l ON l.person_id = p.id
WHERE l.id = $1 AND l.workspace_id = $2
`

type GetPersonByLeadParams struct {
	LeadID      string `json:"lead_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetPersonByLead(ctx context.Context, arg GetPersonByLeadParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByLead, arg.LeadID, arg.WorkspaceID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.Bio,
		&i.Company,
		&i.Location,
		&i.IcpFitScore,
		&i.Confidence,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonIdentity = `-- name: GetPersonIdentity :one
SELECT id, person_id, workspace_id, platform, handle, profile_url, confidence, source, metadata, created_at FROM person_identities
WHERE workspace_id = $1 AND platform = $2 AND handle = $3
`

type GetPersonIdentityParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
	Handle      string `json:"handle"`
}

func (q *Queries) GetPersonIdentity(ctx context.Context, arg GetPersonIdentityParams) (PersonIdentity, error) {
	row := q.db.QueryRow(ctx, getPersonIdentity, arg.WorkspaceID, arg.Platform, arg.Handle)
	var i PersonIdentity
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Confidence,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const linkLeadToPerson = `-- name: LinkLeadToPerson :exec
UPDATE leads
SET person_id = $1
WHERE id = $2 AND workspace_id = $3
`

type LinkLeadToPersonParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	LeadID      string      `json:"lead_id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) LinkLeadToPerson(ctx context.Context, arg LinkLeadToPersonParams) error {
	_, err := q.db.Exec(ctx, linkLeadToPerson, arg.PersonID, arg.LeadID, arg.WorkspaceID)
	return err
}

const listPersonIdentities = `-- name: ListPersonIdentities :many
SELECT id, person_id, workspace_id, platform, handle, profile_url, confidence, source, metadata, created_at FROM person_identities
WHERE person_id = $1 AND workspace_id = $2
ORDER BY confidence DESC, created_at ASC
`

type ListPersonIdentitiesParams struct {
	PersonID    string `json:"person_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListPersonIdentities(ctx context.Context, arg ListPersonIdentitiesParams) ([]PersonIdentity, error) {
	rows, err := q.db.Query(ctx, listPersonIdentities, arg.PersonID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonIdentity{}
	for rows.Next() {
		var i PersonIdentity
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.WorkspaceID,
			&i.Platform,
			&i.Handle,
			&i.ProfileUrl,
			&i.Confidence,
			&i.Source,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET
    display_name = COALESCE($1, display_name),
    bio = COALESCE($2, bio),
    company = COALESCE($3, company),
    location = COALESCE($4, location),
    icp_fit_score = COALESCE($5, icp_fit_score),
    confidence = COALESCE($6, confidence),
    metadata = COALESCE($7, metadata)
WHERE id = $8 AND workspace_id = $9
RETURNING id, workspace_id, display_name, bio, company, location, icp_fit_score, confidence, metadata, created_at, updated_at
`

type UpdatePersonParams struct {
	DisplayName pgtype.Text   `json:"display_name"`
	Bio         pgtype.Text   `json:"bio"`
	Company     pgtype.Text   `json:"company"`
	Location    pgtype.Text   `json:"location"`
	IcpFitScore pgtype.Float4 `json:"icp_fit_score"`
	Confidence  float32       `json:"confidence"`
	Metadata    []byte        `json:"metadata"`
	ID          string        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.DisplayName,
		arg.Bio,
		arg.Company,
		arg.Location,
		arg.IcpFitScore,
		arg.Confidence,
		arg.Metadata,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.Bio,
		&i.Company,
		&i.Location,
		&i.IcpFitScore,
		&i.Confidence,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPersonIdentity = `-- name: UpsertPersonIdentity :one
INSERT INTO person_identities (
    person_id, workspace_id, platform, handle, profile_url, confidence, source, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (workspace_id, platform, handle) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    profile_url = COALESCE(EXCLUDED.profile_url, person_identities.profile_url),
    confidence = GREATEST(person_identities.confidence, EXCLUDED.confidence),
    metadata = person_identities.metadata || EXCLUDED.metadata
RETURNING id, person_id, workspace_id, platform, handle, profile_url, confidence, source, metadata, created_at
`

type UpsertPersonIdentityParams struct {
	PersonID    string      `json:"person_id"`
	WorkspaceID string      `json:"workspace_id"`
	Platform    string      `json:"platform"`
	Handle      string      `json:"handle"`
	ProfileUrl  pgtype.Text `json:"profile_url"`
	Confidence  float32     `json:"confidence"`
	Source      string      `json:"source"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpsertPersonIdentity(ctx context.Context, arg UpsertPersonIdentityParams) (PersonIdentity, error) {
	row := q.db.QueryRow(ctx, upsertPersonIdentity,
		arg.PersonID,
		arg.WorkspaceID,
		arg.Platform,
		arg.Handle,
		arg.ProfileUrl,
		arg.Confidence,
		arg.Source,
		arg.Metadata,
	)
	var i PersonIdentity
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Confidence,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
