// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database

import (
	"context"

	pgvector_go "github.com/pgvector/pgvector-go"
)

const countMonitoringProfiles = `-- name: CountMonitoringProfiles :one
SELECT COUNT(*)::int as count FROM monitoring_profiles
WHERE workspace_id = $1
`

func (q *Queries) CountMonitoringProfiles(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMonitoringProfiles, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createMonitoringProfile = `-- name: CreateMonitoringProfile :one
INSERT INTO monitoring_profiles (workspace_id, name, description, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at
`

type CreateMonitoringProfileParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) CreateMonitoringProfile(ctx context.Context, arg CreateMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, createMonitoringProfile,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPainPointEmbedding = `-- name: CreatePainPointEmbedding :one

INSERT INTO pain_point_embeddings (profile_id, workspace_id, phrase, embedding)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, workspace_id, phrase, embedding, created_at
`

type CreatePainPointEmbeddingParams struct {
	ProfileID   string              `json:"profile_id"`
	WorkspaceID string              `json:"workspace_id"`
	Phrase      string              `json:"phrase"`
	Embedding   *pgvector_go.Vector `json:"embedding"`
}

// ─── Pain-Point Embeddings ─────────────────────────────
func (q *Queries) CreatePainPointEmbedding(ctx context.Context, arg CreatePainPointEmbeddingParams) (PainPointEmbedding, error) {
	row := q.db.QueryRow(ctx, createPainPointEmbedding,
		arg.ProfileID,
		arg.WorkspaceID,
		arg.Phrase,
		arg.Embedding,
	)
	var i PainPointEmbedding
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Phrase,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitoringProfile = `-- name: DeleteMonitoringProfile :exec
DELETE FROM monitoring_profiles
WHERE id = $1 AND workspace_id = $2
`

type DeleteMonitoringProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteMonitoringProfile(ctx context.Context, arg DeleteMonitoringProfileParams) error {
	_, err := q.db.Exec(ctx, deleteMonitoringProfile, arg.ID, arg.WorkspaceID)
	return err
}

const deletePainPointEmbeddingsByProfile = `-- name: DeletePainPointEmbeddingsByProfile :exec
DELETE FROM pain_point_embeddings
WHERE profile_id = $1
`

func (q *Queries) DeletePainPointEmbeddingsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.Exec(ctx, deletePainPointEmbeddingsByProfile, profileID)
	return err
}

const findSimilarPainPoints = `-- name: FindSimilarPainPoints :many
SELECT id, profile_id, workspace_id, phrase,
    (1 - (embedding <=> $1::vector))::float8 as similarity
FROM pain_point_embeddings
WHERE workspace_id = $2
ORDER BY embedding <=> $1::vector
LIMIT $3
`

type FindSimilarPainPointsParams struct {
	QueryEmbedding *pgvector_go.Vector `json:"query_embedding"`
	WorkspaceID    string              `json:"workspace_id"`
	Lim            int32               `json:"lim"`
}

type FindSimilarPainPointsRow struct {
	ID          string  `json:"id"`
	ProfileID   string  `json:"profile_id"`
	WorkspaceID string  `json:"workspace_id"`
	Phrase      string  `json:"phrase"`
	Similarity  float64 `json:"similarity"`
}

func (q *Queries) FindSimilarPainPoints(ctx context.Context, arg FindSimilarPainPointsParams) ([]FindSimilarPainPointsRow, error) {
	rows, err := q.db.Query(ctx, findSimilarPainPoints, arg.QueryEmbedding, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarPainPointsRow{}
	for rows.Next() {
		var i FindSimilarPainPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitoringProfile = `-- name: GetMonitoringProfile :one
SELECT id, workspace_id, name, description, is_active, created_at, updated_at FROM monitoring_profiles
WHERE id = $1 AND workspace_id = $2
`

type GetMonitoringProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMonitoringProfile(ctx context.Context, arg GetMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, getMonitoringProfile, arg.ID, arg.WorkspaceID)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMonitoringProfiles = `-- name: ListActiveMonitoringProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at FROM monitoring_profiles
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listActiveMonitoringProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveProfiles = `-- name: ListAllActiveProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at FROM monitoring_profiles
WHERE is_active = true
ORDER BY workspace_id, created_at DESC
`

func (q *Queries) ListAllActiveProfiles(ctx context.Context) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listAllActiveProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringProfiles = `-- name: ListMonitoringProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at FROM monitoring_profiles
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listMonitoringProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPainPointEmbeddings = `-- name: ListPainPointEmbeddings :many
SELECT id, profile_id, workspace_id, phrase, embedding, created_at FROM pain_point_embeddings
WHERE profile_id = $1
ORDER BY created_at
`

func (q *Queries) ListPainPointEmbeddings(ctx context.Context, profileID string) ([]PainPointEmbedding, error) {
	rows, err := q.db.Query(ctx, listPainPointEmbeddings, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PainPointEmbedding{}
	for rows.Next() {
		var i PainPointEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPainPointEmbeddingsByWorkspace = `-- name: ListPainPointEmbeddingsByWorkspace :many
SELECT id, profile_id, workspace_id, phrase, embedding, created_at FROM pain_point_embeddings
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListPainPointEmbeddingsByWorkspace(ctx context.Context, workspaceID string) ([]PainPointEmbedding, error) {
	rows, err := q.db.Query(ctx, listPainPointEmbeddingsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PainPointEmbedding{}
	for rows.Next() {
		var i PainPointEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitoringProfile = `-- name: UpdateMonitoringProfile :one
UPDATE monitoring_profiles
SET name = $1, description = $2, is_active = $3
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at
`

type UpdateMonitoringProfileParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateMonitoringProfile(ctx context.Context, arg UpdateMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, updateMonitoringProfile,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
		arg.WorkspaceID,
	)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
