// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposals.sql

package database

import (
	"context"
)

const countHumanProposalsByStatus = `-- name: CountHumanProposalsByStatus :many
SELECT status, COUNT(*)::int AS count
FROM human_proposals
WHERE workspace_id = $1
GROUP BY status
`

type CountHumanProposalsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountHumanProposalsByStatus(ctx context.Context, workspaceID string) ([]CountHumanProposalsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countHumanProposalsByStatus, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHumanProposalsByStatusRow{}
	for rows.Next() {
		var i CountHumanProposalsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createHumanProposal = `-- name: CreateHumanProposal :one
INSERT INTO human_proposals (
    workspace_id, proposal_type, title, body, status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, workspace_id, proposal_type, title, body, status, metadata, created_at, updated_at
`

type CreateHumanProposalParams struct {
	WorkspaceID  string `json:"workspace_id"`
	ProposalType string `json:"proposal_type"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	Status       string `json:"status"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) CreateHumanProposal(ctx context.Context, arg CreateHumanProposalParams) (HumanProposal, error) {
	row := q.db.QueryRow(ctx, createHumanProposal,
		arg.WorkspaceID,
		arg.ProposalType,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Metadata,
	)
	var i HumanProposal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProposalType,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHumanProposals = `-- name: ListHumanProposals :many
SELECT id, workspace_id, proposal_type, title, body, status, metadata, created_at, updated_at FROM human_proposals
WHERE workspace_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListHumanProposalsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Status      string `json:"status"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
}

func (q *Queries) ListHumanProposals(ctx context.Context, arg ListHumanProposalsParams) ([]HumanProposal, error) {
	rows, err := q.db.Query(ctx, listHumanProposals,
		arg.WorkspaceID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HumanProposal{}
	for rows.Next() {
		var i HumanProposal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProposalType,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHumanProposalStatus = `-- name: UpdateHumanProposalStatus :one
UPDATE human_proposals
SET status = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, proposal_type, title, body, status, metadata, created_at, updated_at
`

type UpdateHumanProposalStatusParams struct {
	Status      string `json:"status"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateHumanProposalStatus(ctx context.Context, arg UpdateHumanProposalStatusParams) (HumanProposal, error) {
	row := q.db.QueryRow(ctx, updateHumanProposalStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i HumanProposal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProposalType,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
