// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	AssignMention(ctx context.Context, arg AssignMentionParams) (Mention, error)
	ConversionFunnel(ctx context.Context, workspaceID string) ([]ConversionFunnelRow, error)
	CountActiveKeywords(ctx context.Context, workspaceID string) (int32, error)
	CountConvertedLeads(ctx context.Context, workspaceID string) (int32, error)
	CountDocuments(ctx context.Context, workspaceID string) (int32, error)
	CountKeywords(ctx context.Context, workspaceID string) (int32, error)
	CountLeadsByStage(ctx context.Context, workspaceID string) ([]CountLeadsByStageRow, error)
	CountMentions30d(ctx context.Context, workspaceID string) (int32, error)
	CountMentionsByPlatform(ctx context.Context, workspaceID string) ([]CountMentionsByPlatformRow, error)
	CountMentionsByStatus(ctx context.Context, workspaceID string) ([]CountMentionsByStatusRow, error)
	CountMentionsByTier(ctx context.Context, workspaceID string) ([]CountMentionsByTierRow, error)
	CountMonitoringProfiles(ctx context.Context, workspaceID string) (int32, error)
	CountNewMentions(ctx context.Context, workspaceID string) (int32, error)
	CountNotifications(ctx context.Context, workspaceID string) (int32, error)
	CountRepliesByStatus(ctx context.Context, workspaceID string) ([]CountRepliesByStatusRow, error)
	CountRepliesPosted30d(ctx context.Context, workspaceID string) (int32, error)
	CountTotalLeads(ctx context.Context, workspaceID string) (int32, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateExtensionToken(ctx context.Context, arg CreateExtensionTokenParams) (ExtensionToken, error)
	CreateKeyword(ctx context.Context, arg CreateKeywordParams) (CreateKeywordRow, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateLeadEvent(ctx context.Context, arg CreateLeadEventParams) (LeadEvent, error)
	CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error)
	CreateMonitoringProfile(ctx context.Context, arg CreateMonitoringProfileParams) (MonitoringProfile, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ─── Pain-Point Embeddings ─────────────────────────────
	CreatePainPointEmbedding(ctx context.Context, arg CreatePainPointEmbeddingParams) (PainPointEmbedding, error)
	CreateReply(ctx context.Context, arg CreateReplyParams) (Reply, error)
	CreateUTMLink(ctx context.Context, arg CreateUTMLinkParams) (UtmLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error
	DeleteExtensionTokenByWorkspace(ctx context.Context, workspaceID string) error
	DeleteKeyword(ctx context.Context, arg DeleteKeywordParams) error
	DeleteMonitoringProfile(ctx context.Context, arg DeleteMonitoringProfileParams) error
	DeletePainPointEmbeddingsByProfile(ctx context.Context, profileID string) error
	DeletePlatformSession(ctx context.Context, arg DeletePlatformSessionParams) error
	DeleteUTMLink(ctx context.Context, arg DeleteUTMLinkParams) error
	FindSimilarPainPoints(ctx context.Context, arg FindSimilarPainPointsParams) ([]FindSimilarPainPointsRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetExtensionTokenByToken(ctx context.Context, token string) (ExtensionToken, error)
	GetExtensionTokenByWorkspace(ctx context.Context, workspaceID string) (ExtensionToken, error)
	GetKeyword(ctx context.Context, arg GetKeywordParams) (GetKeywordRow, error)
	GetLead(ctx context.Context, arg GetLeadParams) (Lead, error)
	GetMention(ctx context.Context, arg GetMentionParams) (Mention, error)
	GetMonitoringProfile(ctx context.Context, arg GetMonitoringProfileParams) (MonitoringProfile, error)
	GetPlatformSession(ctx context.Context, arg GetPlatformSessionParams) (PlatformAccount, error)
	GetReply(ctx context.Context, arg GetReplyParams) (Reply, error)
	GetUTMLinkByCode(ctx context.Context, code string) (UtmLink, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceSettings(ctx context.Context, id string) ([]byte, error)
	IncrementUTMClicks(ctx context.Context, code string) error
	ListActiveKeywords(ctx context.Context, workspaceID string) ([]ListActiveKeywordsRow, error)
	ListActiveMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error)
	ListAllActiveKeywords(ctx context.Context) ([]ListAllActiveKeywordsRow, error)
	ListAllActiveProfiles(ctx context.Context) ([]MonitoringProfile, error)
	ListApprovedRepliesByWorkspace(ctx context.Context, workspaceID string) ([]ListApprovedRepliesByWorkspaceRow, error)
	ListDocuments(ctx context.Context, workspaceID string) ([]Document, error)
	ListKeywords(ctx context.Context, workspaceID string) ([]ListKeywordsRow, error)
	ListLeadEvents(ctx context.Context, leadID string) ([]LeadEvent, error)
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error)
	ListLeadsByStage(ctx context.Context, arg ListLeadsByStageParams) ([]Lead, error)
	ListMentions(ctx context.Context, arg ListMentionsParams) ([]Mention, error)
	ListMentionsByIntent(ctx context.Context, arg ListMentionsByIntentParams) ([]Mention, error)
	ListMentionsByPlatform(ctx context.Context, arg ListMentionsByPlatformParams) ([]Mention, error)
	ListMentionsByStatus(ctx context.Context, arg ListMentionsByStatusParams) ([]Mention, error)
	ListMentionsFiltered(ctx context.Context, arg ListMentionsFilteredParams) ([]Mention, error)
	// ─── Smart Inbox Tiers ────────────────────────────────
	ListMentionsLeadsReady(ctx context.Context, arg ListMentionsLeadsReadyParams) ([]Mention, error)
	ListMentionsWorthWatching(ctx context.Context, arg ListMentionsWorthWatchingParams) ([]Mention, error)
	ListMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPainPointEmbeddings(ctx context.Context, profileID string) ([]PainPointEmbedding, error)
	ListPainPointEmbeddingsByWorkspace(ctx context.Context, workspaceID string) ([]PainPointEmbedding, error)
	ListPlatformSessions(ctx context.Context, workspaceID string) ([]PlatformAccount, error)
	ListRecentLeadsForWorkspace(ctx context.Context, arg ListRecentLeadsForWorkspaceParams) ([]ListRecentLeadsForWorkspaceRow, error)
	ListRepliesByMention(ctx context.Context, arg ListRepliesByMentionParams) ([]Reply, error)
	ListUTMLinksByWorkspace(ctx context.Context, workspaceID string) ([]UtmLink, error)
	ListUnclassifiedMentions(ctx context.Context, arg ListUnclassifiedMentionsParams) ([]Mention, error)
	ListUsersByExternalID(ctx context.Context, clerkUserID string) ([]User, error)
	MarkReplyPosted(ctx context.Context, arg MarkReplyPostedParams) (Reply, error)
	MentionsPerDay(ctx context.Context, workspaceID string) ([]MentionsPerDayRow, error)
	MentionsPerIntent(ctx context.Context, workspaceID string) ([]MentionsPerIntentRow, error)
	MentionsPerPlatform(ctx context.Context, workspaceID string) ([]MentionsPerPlatformRow, error)
	ReplyStats(ctx context.Context, workspaceID string) ([]ReplyStatsRow, error)
	SearchMentions(ctx context.Context, arg SearchMentionsParams) ([]Mention, error)
	TopKeywords(ctx context.Context, workspaceID string) ([]TopKeywordsRow, error)
	TouchExtensionToken(ctx context.Context, token string) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentChunkCount(ctx context.Context, arg UpdateDocumentChunkCountParams) error
	UpdateKeyword(ctx context.Context, arg UpdateKeywordParams) (UpdateKeywordRow, error)
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	UpdateLeadStage(ctx context.Context, arg UpdateLeadStageParams) (Lead, error)
	// ─── Embedding & Scoring ──────────────────────────────
	UpdateMentionEmbedding(ctx context.Context, arg UpdateMentionEmbeddingParams) error
	UpdateMentionIntent(ctx context.Context, arg UpdateMentionIntentParams) (Mention, error)
	UpdateMentionScoring(ctx context.Context, arg UpdateMentionScoringParams) (Mention, error)
	UpdateMentionStatus(ctx context.Context, arg UpdateMentionStatusParams) (Mention, error)
	UpdateMonitoringProfile(ctx context.Context, arg UpdateMonitoringProfileParams) (MonitoringProfile, error)
	UpdateReplyContent(ctx context.Context, arg UpdateReplyContentParams) (Reply, error)
	UpdateReplyStatus(ctx context.Context, arg UpdateReplyStatusParams) (Reply, error)
	UpdateWorkspaceSettings(ctx context.Context, arg UpdateWorkspaceSettingsParams) error
	UpsertPlatformSession(ctx context.Context, arg UpsertPlatformSessionParams) (PlatformAccount, error)
}

var _ Querier = (*Queries)(nil)
