// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reply_engagements.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplyEngagement = `-- name: CreateReplyEngagement :one
INSERT INTO reply_engagements (
    reply_id, workspace_id, upvotes, downvotes, reply_count, is_removed, checked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
) RETURNING id, reply_id, workspace_id, upvotes, downvotes, reply_count, is_removed, checked_at, created_at
`

type CreateReplyEngagementParams struct {
	ReplyID     string `json:"reply_id"`
	WorkspaceID string `json:"workspace_id"`
	Upvotes     int32  `json:"upvotes"`
	Downvotes   int32  `json:"downvotes"`
	ReplyCount  int32  `json:"reply_count"`
	IsRemoved   bool   `json:"is_removed"`
}

func (q *Queries) CreateReplyEngagement(ctx context.Context, arg CreateReplyEngagementParams) (ReplyEngagement, error) {
	row := q.db.QueryRow(ctx, createReplyEngagement,
		arg.ReplyID,
		arg.WorkspaceID,
		arg.Upvotes,
		arg.Downvotes,
		arg.ReplyCount,
		arg.IsRemoved,
	)
	var i ReplyEngagement
	err := row.Scan(
		&i.ID,
		&i.ReplyID,
		&i.WorkspaceID,
		&i.Upvotes,
		&i.Downvotes,
		&i.ReplyCount,
		&i.IsRemoved,
		&i.CheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestReplyEngagement = `-- name: GetLatestReplyEngagement :one
SELECT id, reply_id, workspace_id, upvotes, downvotes, reply_count, is_removed, checked_at, created_at FROM reply_engagements
WHERE reply_id = $1
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLatestReplyEngagement(ctx context.Context, replyID string) (ReplyEngagement, error) {
	row := q.db.QueryRow(ctx, getLatestReplyEngagement, replyID)
	var i ReplyEngagement
	err := row.Scan(
		&i.ID,
		&i.ReplyID,
		&i.WorkspaceID,
		&i.Upvotes,
		&i.Downvotes,
		&i.ReplyCount,
		&i.IsRemoved,
		&i.CheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPostedRepliesSince = `-- name: ListPostedRepliesSince :many
SELECT r.id, r.mention_id, r.workspace_id, r.content,
       m.url, m.platform
FROM replies r
JOIN mentions m ON r.mention_id = m.id
WHERE r.status = 'posted'
AND r.posted_at >= $1
ORDER BY r.posted_at DESC
`

type ListPostedRepliesSinceRow struct {
	ID          string `json:"id"`
	MentionID   string `json:"mention_id"`
	WorkspaceID string `json:"workspace_id"`
	Content     string `json:"content"`
	Url         string `json:"url"`
	Platform    string `json:"platform"`
}

func (q *Queries) ListPostedRepliesSince(ctx context.Context, since pgtype.Timestamptz) ([]ListPostedRepliesSinceRow, error) {
	rows, err := q.db.Query(ctx, listPostedRepliesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostedRepliesSinceRow{}
	for rows.Next() {
		var i ListPostedRepliesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.MentionID,
			&i.WorkspaceID,
			&i.Content,
			&i.Url,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplyEngagements = `-- name: ListReplyEngagements :many
SELECT id, reply_id, workspace_id, upvotes, downvotes, reply_count, is_removed, checked_at, created_at FROM reply_engagements
WHERE reply_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type ListReplyEngagementsParams struct {
	ReplyID string `json:"reply_id"`
	Lim     int32  `json:"lim"`
}

func (q *Queries) ListReplyEngagements(ctx context.Context, arg ListReplyEngagementsParams) ([]ReplyEngagement, error) {
	rows, err := q.db.Query(ctx, listReplyEngagements, arg.ReplyID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplyEngagement{}
	for rows.Next() {
		var i ReplyEngagement
		if err := rows.Scan(
			&i.ID,
			&i.ReplyID,
			&i.WorkspaceID,
			&i.Upvotes,
			&i.Downvotes,
			&i.ReplyCount,
			&i.IsRemoved,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
