// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRepliesByStatus = `-- name: CountRepliesByStatus :many
SELECT status, COUNT(*)::int as count
FROM replies
WHERE workspace_id = $1
GROUP BY status
`

type CountRepliesByStatusRow struct {
	Status ReplyStatus `json:"status"`
	Count  int32       `json:"count"`
}

func (q *Queries) CountRepliesByStatus(ctx context.Context, workspaceID string) ([]CountRepliesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRepliesByStatus, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRepliesByStatusRow{}
	for rows.Next() {
		var i CountRepliesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReply = `-- name: CreateReply :one
INSERT INTO replies (
    mention_id, workspace_id, content, status, template_style, thread_context_used
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used
`

type CreateReplyParams struct {
	MentionID         string      `json:"mention_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Content           string      `json:"content"`
	Status            ReplyStatus `json:"status"`
	TemplateStyle     pgtype.Text `json:"template_style"`
	ThreadContextUsed bool        `json:"thread_context_used"`
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (Reply, error) {
	row := q.db.QueryRow(ctx, createReply,
		arg.MentionID,
		arg.WorkspaceID,
		arg.Content,
		arg.Status,
		arg.TemplateStyle,
		arg.ThreadContextUsed,
	)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
	)
	return i, err
}

const getReply = `-- name: GetReply :one
SELECT id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used FROM replies
WHERE id = $1 AND workspace_id = $2
`

type GetReplyParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetReply(ctx context.Context, arg GetReplyParams) (Reply, error) {
	row := q.db.QueryRow(ctx, getReply, arg.ID, arg.WorkspaceID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
	)
	return i, err
}

const listApprovedRepliesByWorkspace = `-- name: ListApprovedRepliesByWorkspace :many
SELECT r.id, r.content, r.edited_content,
       m.id AS mention_id, m.platform, m.url, m.title
FROM replies r
JOIN mentions m ON r.mention_id = m.id
WHERE r.workspace_id = $1 AND r.status = 'approved'
ORDER BY r.created_at DESC
`

type ListApprovedRepliesByWorkspaceRow struct {
	ID            string      `json:"id"`
	Content       string      `json:"content"`
	EditedContent pgtype.Text `json:"edited_content"`
	MentionID     string      `json:"mention_id"`
	Platform      string      `json:"platform"`
	Url           string      `json:"url"`
	Title         pgtype.Text `json:"title"`
}

func (q *Queries) ListApprovedRepliesByWorkspace(ctx context.Context, workspaceID string) ([]ListApprovedRepliesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listApprovedRepliesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedRepliesByWorkspaceRow{}
	for rows.Next() {
		var i ListApprovedRepliesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.EditedContent,
			&i.MentionID,
			&i.Platform,
			&i.Url,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepliesByMention = `-- name: ListRepliesByMention :many
SELECT id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used FROM replies
WHERE mention_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
`

type ListRepliesByMentionParams struct {
	MentionID   string `json:"mention_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListRepliesByMention(ctx context.Context, arg ListRepliesByMentionParams) ([]Reply, error) {
	rows, err := q.db.Query(ctx, listRepliesByMention, arg.MentionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reply{}
	for rows.Next() {
		var i Reply
		if err := rows.Scan(
			&i.ID,
			&i.MentionID,
			&i.WorkspaceID,
			&i.Content,
			&i.EditedContent,
			&i.Status,
			&i.PlatformPostID,
			&i.PostedBy,
			&i.ApprovedBy,
			&i.UtmLinkID,
			&i.SafeLinkScore,
			&i.SafeLinkFlags,
			&i.PostedAt,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateStyle,
			&i.ThreadContextUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReplyPosted = `-- name: MarkReplyPosted :one
UPDATE replies
SET status = 'posted', posted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used
`

type MarkReplyPostedParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkReplyPosted(ctx context.Context, arg MarkReplyPostedParams) (Reply, error) {
	row := q.db.QueryRow(ctx, markReplyPosted, arg.ID, arg.WorkspaceID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
	)
	return i, err
}

const updateReplyContent = `-- name: UpdateReplyContent :one
UPDATE replies
SET edited_content = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used
`

type UpdateReplyContentParams struct {
	EditedContent pgtype.Text `json:"edited_content"`
	ID            string      `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
}

func (q *Queries) UpdateReplyContent(ctx context.Context, arg UpdateReplyContentParams) (Reply, error) {
	row := q.db.QueryRow(ctx, updateReplyContent, arg.EditedContent, arg.ID, arg.WorkspaceID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
	)
	return i, err
}

const updateReplyStatus = `-- name: UpdateReplyStatus :one
UPDATE replies
SET status = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, mention_id, workspace_id, content, edited_content, status, platform_post_id, posted_by, approved_by, utm_link_id, safe_link_score, safe_link_flags, posted_at, approved_at, created_at, updated_at, template_style, thread_context_used
`

type UpdateReplyStatusParams struct {
	Status      ReplyStatus `json:"status"`
	ID          string      `json:"id"`
	WorkspaceID string      `json:"workspace_id"`
}

func (q *Queries) UpdateReplyStatus(ctx context.Context, arg UpdateReplyStatusParams) (Reply, error) {
	row := q.db.QueryRow(ctx, updateReplyStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.WorkspaceID,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.PlatformPostID,
		&i.PostedBy,
		&i.ApprovedBy,
		&i.UtmLinkID,
		&i.SafeLinkScore,
		&i.SafeLinkFlags,
		&i.PostedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateStyle,
		&i.ThreadContextUsed,
	)
	return i, err
}
