// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlatformSession = `-- name: DeletePlatformSession :exec
DELETE FROM platform_accounts
WHERE workspace_id = $1
  AND platform = $2::platform_type
`

type DeletePlatformSessionParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) DeletePlatformSession(ctx context.Context, arg DeletePlatformSessionParams) error {
	_, err := q.db.Exec(ctx, deletePlatformSession, arg.WorkspaceID, arg.Platform)
	return err
}

const getPlatformSession = `-- name: GetPlatformSession :one
SELECT id, workspace_id, user_id, platform, username, platform_user_id, access_token_enc, refresh_token_enc, token_expires_at, karma, account_age_days, trust_score, is_active, metadata, created_at, updated_at FROM platform_accounts
WHERE workspace_id = $1
  AND platform = $2::platform_type
LIMIT 1
`

type GetPlatformSessionParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) GetPlatformSession(ctx context.Context, arg GetPlatformSessionParams) (PlatformAccount, error) {
	row := q.db.QueryRow(ctx, getPlatformSession, arg.WorkspaceID, arg.Platform)
	var i PlatformAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Platform,
		&i.Username,
		&i.PlatformUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Karma,
		&i.AccountAgeDays,
		&i.TrustScore,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformSessions = `-- name: ListPlatformSessions :many
SELECT id, workspace_id, user_id, platform, username, platform_user_id, access_token_enc, refresh_token_enc, token_expires_at, karma, account_age_days, trust_score, is_active, metadata, created_at, updated_at FROM platform_accounts
WHERE workspace_id = $1
  AND is_active = true
ORDER BY platform
`

func (q *Queries) ListPlatformSessions(ctx context.Context, workspaceID string) ([]PlatformAccount, error) {
	rows, err := q.db.Query(ctx, listPlatformSessions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAccount{}
	for rows.Next() {
		var i PlatformAccount
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Platform,
			&i.Username,
			&i.PlatformUserID,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.TokenExpiresAt,
			&i.Karma,
			&i.AccountAgeDays,
			&i.TrustScore,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlatformSession = `-- name: UpsertPlatformSession :one
INSERT INTO platform_accounts (workspace_id, user_id, platform, username, access_token_enc, is_active, metadata)
VALUES ($1, $2, $3::platform_type, $4, $5, true, $6)
ON CONFLICT (workspace_id, user_id, platform)
DO UPDATE SET
    access_token_enc = EXCLUDED.access_token_enc,
    username         = EXCLUDED.username,
    is_active        = true,
    metadata         = EXCLUDED.metadata,
    updated_at       = NOW()
RETURNING id, workspace_id, user_id, platform, username, platform_user_id, access_token_enc, refresh_token_enc, token_expires_at, karma, account_age_days, trust_score, is_active, metadata, created_at, updated_at
`

type UpsertPlatformSessionParams struct {
	WorkspaceID    string      `json:"workspace_id"`
	UserID         string      `json:"user_id"`
	Platform       string      `json:"platform"`
	Username       pgtype.Text `json:"username"`
	AccessTokenEnc pgtype.Text `json:"access_token_enc"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) UpsertPlatformSession(ctx context.Context, arg UpsertPlatformSessionParams) (PlatformAccount, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSession,
		arg.WorkspaceID,
		arg.UserID,
		arg.Platform,
		arg.Username,
		arg.AccessTokenEnc,
		arg.Metadata,
	)
	var i PlatformAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Platform,
		&i.Username,
		&i.PlatformUserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Karma,
		&i.AccountAgeDays,
		&i.TrustScore,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
