// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package database

import (
	"context"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    mention_id, platform, thread_id, content, fetched_at
) VALUES (
    $1, $2, $3, $4, NOW()
) RETURNING id, mention_id, platform, thread_id, content, summary, sentiment, solutions_mentioned, our_product_mentioned, fetched_at, created_at
`

type CreateThreadParams struct {
	MentionID string `json:"mention_id"`
	Platform  string `json:"platform"`
	ThreadID  string `json:"thread_id"`
	Content   []byte `json:"content"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.MentionID,
		arg.Platform,
		arg.ThreadID,
		arg.Content,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Platform,
		&i.ThreadID,
		&i.Content,
		&i.Summary,
		&i.Sentiment,
		&i.SolutionsMentioned,
		&i.OurProductMentioned,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadByMention = `-- name: GetThreadByMention :one
SELECT id, mention_id, platform, thread_id, content, summary, sentiment, solutions_mentioned, our_product_mentioned, fetched_at, created_at FROM threads
WHERE mention_id = $1
LIMIT 1
`

func (q *Queries) GetThreadByMention(ctx context.Context, mentionID string) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByMention, mentionID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Platform,
		&i.ThreadID,
		&i.Content,
		&i.Summary,
		&i.Sentiment,
		&i.SolutionsMentioned,
		&i.OurProductMentioned,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateThreadContent = `-- name: UpdateThreadContent :one
UPDATE threads
SET content = $1, fetched_at = NOW()
WHERE id = $2
RETURNING id, mention_id, platform, thread_id, content, summary, sentiment, solutions_mentioned, our_product_mentioned, fetched_at, created_at
`

type UpdateThreadContentParams struct {
	Content []byte `json:"content"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateThreadContent(ctx context.Context, arg UpdateThreadContentParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThreadContent, arg.Content, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.MentionID,
		&i.Platform,
		&i.ThreadID,
		&i.Content,
		&i.Summary,
		&i.Sentiment,
		&i.SolutionsMentioned,
		&i.OurProductMentioned,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}
