// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: utm_links.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUTMLink = `-- name: CreateUTMLink :one
INSERT INTO utm_links (workspace_id, code, destination_url, utm_source, utm_medium, utm_campaign, utm_content)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, code, destination_url, utm_source, utm_medium, utm_campaign, utm_content, click_count, signup_count, revenue_cents, created_at
`

type CreateUTMLinkParams struct {
	WorkspaceID    string      `json:"workspace_id"`
	Code           string      `json:"code"`
	DestinationUrl string      `json:"destination_url"`
	UtmSource      string      `json:"utm_source"`
	UtmMedium      string      `json:"utm_medium"`
	UtmCampaign    pgtype.Text `json:"utm_campaign"`
	UtmContent     pgtype.Text `json:"utm_content"`
}

func (q *Queries) CreateUTMLink(ctx context.Context, arg CreateUTMLinkParams) (UtmLink, error) {
	row := q.db.QueryRow(ctx, createUTMLink,
		arg.WorkspaceID,
		arg.Code,
		arg.DestinationUrl,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmContent,
	)
	var i UtmLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.DestinationUrl,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmContent,
		&i.ClickCount,
		&i.SignupCount,
		&i.RevenueCents,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUTMLink = `-- name: DeleteUTMLink :exec
DELETE FROM utm_links WHERE id = $1 AND workspace_id = $2
`

type DeleteUTMLinkParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteUTMLink(ctx context.Context, arg DeleteUTMLinkParams) error {
	_, err := q.db.Exec(ctx, deleteUTMLink, arg.ID, arg.WorkspaceID)
	return err
}

const getUTMLinkByCode = `-- name: GetUTMLinkByCode :one
SELECT id, workspace_id, code, destination_url, utm_source, utm_medium, utm_campaign, utm_content, click_count, signup_count, revenue_cents, created_at FROM utm_links WHERE code = $1
`

func (q *Queries) GetUTMLinkByCode(ctx context.Context, code string) (UtmLink, error) {
	row := q.db.QueryRow(ctx, getUTMLinkByCode, code)
	var i UtmLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.DestinationUrl,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmContent,
		&i.ClickCount,
		&i.SignupCount,
		&i.RevenueCents,
		&i.CreatedAt,
	)
	return i, err
}

const incrementUTMClicks = `-- name: IncrementUTMClicks :exec
UPDATE utm_links SET click_count = click_count + 1 WHERE code = $1
`

func (q *Queries) IncrementUTMClicks(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, incrementUTMClicks, code)
	return err
}

const listUTMLinksByWorkspace = `-- name: ListUTMLinksByWorkspace :many
SELECT id, workspace_id, code, destination_url, utm_source, utm_medium, utm_campaign, utm_content, click_count, signup_count, revenue_cents, created_at FROM utm_links WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUTMLinksByWorkspace(ctx context.Context, workspaceID string) ([]UtmLink, error) {
	rows, err := q.db.Query(ctx, listUTMLinksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UtmLink{}
	for rows.Next() {
		var i UtmLink
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.DestinationUrl,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmContent,
			&i.ClickCount,
			&i.SignupCount,
			&i.RevenueCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
