// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowExecution = `-- name: CreateWorkflowExecution :one
INSERT INTO workflow_executions (
    workflow_id, mention_id, status, steps, current_step
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workflow_id, mention_id, status, steps, current_step, error_message, started_at, completed_at, created_at
`

type CreateWorkflowExecutionParams struct {
	WorkflowID  string          `json:"workflow_id"`
	MentionID   pgtype.UUID     `json:"mention_id"`
	Status      ExecutionStatus `json:"status"`
	Steps       []byte          `json:"steps"`
	CurrentStep int32           `json:"current_step"`
}

func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecution,
		arg.WorkflowID,
		arg.MentionID,
		arg.Status,
		arg.Steps,
		arg.CurrentStep,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.MentionID,
		&i.Status,
		&i.Steps,
		&i.CurrentStep,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasWorkflowExecutionForMention = `-- name: HasWorkflowExecutionForMention :one
SELECT EXISTS(
    SELECT 1 FROM workflow_executions
    WHERE workflow_id = $1 AND mention_id = $2
) AS exists
`

type HasWorkflowExecutionForMentionParams struct {
	WorkflowID string      `json:"workflow_id"`
	MentionID  pgtype.UUID `json:"mention_id"`
}

func (q *Queries) HasWorkflowExecutionForMention(ctx context.Context, arg HasWorkflowExecutionForMentionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWorkflowExecutionForMention, arg.WorkflowID, arg.MentionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementWorkflowTriggerCount = `-- name: IncrementWorkflowTriggerCount :one
UPDATE workflows
SET execution_count = execution_count + 1,
    last_triggered_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, description, status, trigger_config, action_chain, max_triggers_per_hour, execution_count, last_triggered_at, created_by, created_at, updated_at
`

func (q *Queries) IncrementWorkflowTriggerCount(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRow(ctx, incrementWorkflowTriggerCount, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.TriggerConfig,
		&i.ActionChain,
		&i.MaxTriggersPerHour,
		&i.ExecutionCount,
		&i.LastTriggeredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflowsByWorkspace = `-- name: ListActiveWorkflowsByWorkspace :many
SELECT id, workspace_id, name, description, status, trigger_config, action_chain, max_triggers_per_hour, execution_count, last_triggered_at, created_by, created_at, updated_at FROM workflows
WHERE workspace_id = $1 AND status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveWorkflowsByWorkspace(ctx context.Context, workspaceID string) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.TriggerConfig,
			&i.ActionChain,
			&i.MaxTriggersPerHour,
			&i.ExecutionCount,
			&i.LastTriggeredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowExecution = `-- name: UpdateWorkflowExecution :one
UPDATE workflow_executions
SET status = $1,
    current_step = $2,
    steps = $3,
    error_message = $4,
    completed_at = $5
WHERE id = $6
RETURNING id, workflow_id, mention_id, status, steps, current_step, error_message, started_at, completed_at, created_at
`

type UpdateWorkflowExecutionParams struct {
	Status       ExecutionStatus    `json:"status"`
	CurrentStep  int32              `json:"current_step"`
	Steps        []byte             `json:"steps"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ID           string             `json:"id"`
}

func (q *Queries) UpdateWorkflowExecution(ctx context.Context, arg UpdateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecution,
		arg.Status,
		arg.CurrentStep,
		arg.Steps,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.ID,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.MentionID,
		&i.Status,
		&i.Steps,
		&i.CurrentStep,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
