// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package database

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (clerk_org_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, clerk_org_id, name, slug, tier, stripe_customer_id, settings, keyword_limit, mention_limit, seat_limit, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ClerkOrgID string `json:"clerk_org_id"`
	Name       string `json:"name"`
	Slug       string `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ClerkOrgID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.Slug,
		&i.Tier,
		&i.StripeCustomerID,
		&i.Settings,
		&i.KeywordLimit,
		&i.MentionLimit,
		&i.SeatLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, clerk_org_id, name, slug, tier, stripe_customer_id, settings, keyword_limit, mention_limit, seat_limit, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.Slug,
		&i.Tier,
		&i.StripeCustomerID,
		&i.Settings,
		&i.KeywordLimit,
		&i.MentionLimit,
		&i.SeatLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, clerk_org_id, name, slug, tier, stripe_customer_id, settings, keyword_limit, mention_limit, seat_limit, created_at, updated_at FROM workspaces WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.Slug,
		&i.Tier,
		&i.StripeCustomerID,
		&i.Settings,
		&i.KeywordLimit,
		&i.MentionLimit,
		&i.SeatLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceSettings = `-- name: GetWorkspaceSettings :one
SELECT settings FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceSettings(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSettings, id)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const updateWorkspaceSettings = `-- name: UpdateWorkspaceSettings :exec
UPDATE workspaces SET settings = $1 WHERE id = $2
`

type UpdateWorkspaceSettingsParams struct {
	Settings []byte `json:"settings"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateWorkspaceSettings(ctx context.Context, arg UpdateWorkspaceSettingsParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceSettings, arg.Settings, arg.ID)
	return err
}
