// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/hackernews.js"
    | "/content-scripts/linkedin.js"
    | "/content-scripts/reddit.js"
    | "/content-scripts/twitter.js"
    | "/icons/icon-128.png"
    | "/icons/icon-16.png"
    | "/icons/icon-32.png"
    | "/icons/icon-48.png"
    | "/popup.html"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
